// frontend/apps/web-next/src/components/ui/switch.tsx
"use client";

import * as React from "react";
import { Switch as SwitchPrimitive } from "radix-ui";

import { cn } from "@/lib/utils";

function Switch({
  className,
  size = "default",
  ...props
}: React.ComponentProps<typeof SwitchPrimitive.Root> & {
  size?: "sm" | "default";
}) {
  return (
    <SwitchPrimitive.Root
      data-slot="switch"
      data-size={size}
      className={cn(
        "peer group/switch data-[state=checked]:bg-primary data-[state=unchecked]:bg-input focus-visible:outline-ring relative inline-flex shrink-0 items-center rounded-full border border-transparent shadow-xs transition-all focus-visible:outline-2 focus-visible:outline-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[size=default]:h-[1.15rem] data-[size=default]:w-8 data-[size=sm]:h-3.5 data-[size=sm]:w-6",
        // The track takes pointer input on a larger, invisible area: at least
        // 24 px (WCAG 2.5.8), 44 px on a coarse pointer (ACCESSIBILITY.md).
        "after:absolute after:-inset-x-1 after:-inset-y-1.5 pointer-coarse:after:-inset-x-2.5 pointer-coarse:after:-inset-y-4",
        className
      )}
      {...props}
    >
      <SwitchPrimitive.Thumb
        data-slot="switch-thumb"
        className={cn(
          "bg-background dark:data-[state=checked]:bg-primary-foreground dark:data-[state=unchecked]:bg-foreground pointer-events-none block rounded-full ring-0 transition-transform group-data-[size=default]/switch:size-4 group-data-[size=sm]/switch:size-3 data-[state=checked]:translate-x-[calc(100%-2px)] data-[state=unchecked]:translate-x-0"
        )}
      />
    </SwitchPrimitive.Root>
  );
}

export { Switch };

// frontend/packages/ui/src/lib/Input/Switch.svelte
<script lang="ts">
  import { createSwitch } from "@melt-ui/svelte";
  import { writable } from "svelte/store";
  import { uid } from "uid";

  let cls = "";
  export { cls as class };
  export let value = false;
  export let disabled = false;
  export let sideEffect: ((params: { current: boolean; next: boolean }) => void) | undefined =
    undefined;

  const checked = writable(value);

  const {
    elements: { root, input },
    options
  } = createSwitch({
    checked,
    onCheckedChange({ curr, next }) {
      sideEffect?.({ current: curr, next });
      value = next;
      return next;
    },
    disabled
  });

  const label_id = uid(8);
  const id = uid(8);
  const check_id = uid(8);

  $: checked.set(value);
  $: options.disabled.set(disabled);
</script>

<fieldset class="flex items-center gap-4 {cls}">
  <label class="flex-grow" for={id} id={label_id}>
    <slot />
  </label>
  <button
    {...$root}
    use:root
    class="bg-tertiary data-[state=checked]:bg-accent-default relative h-6 cursor-pointer rounded-full transition-colors disabled:cursor-not-allowed"
    {id}
    aria-labelledby={label_id}
  >
    <span class="thumb block rounded-full bg-[var(--text-on-fill)] transition"></span>
  </button>
  <input {...$input} use:input id={check_id} />
</fieldset>

<style>
  button {
    --w: 2.75rem;
    --padding: 0.15rem;
    width: var(--w);
    min-width: var(--w);
    box-shadow: 0 0 0 1px var(--border-stronger);
  }

  .thumb {
    --size: 1.25rem;
    width: var(--size);
    height: var(--size);
    transform: translateX(var(--padding));
  }

  :global([data-state="checked"]) .thumb {
    transform: translateX(calc(var(--w) - var(--size) - var(--padding)));
  }
</style>
