// frontend/apps/web-next/src/components/shell/profile-menu.tsx
"use client";

import { Building2, Globe, KeyRound, LogOut, Sparkles, User } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useLocale, useTranslations } from "next-intl";
import { useTransition } from "react";
import { useAppContext } from "@/components/providers/app-context";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu";
import { setLocale } from "@/lib/i18n/actions";
import { locales } from "@/lib/i18n/locales";
import { useWhatsNew } from "@/features/whats-new/whats-new-provider";

const LOCALE_LABELS: Record<string, string> = { sv: "Svenska", en: "English" };

export function ProfileMenu() {
  const t = useTranslations();
  const { user, federationStatus } = useAppContext();
  const { enabled: whatsNewEnabled, hasUnseen } = useWhatsNew();
  const locale = useLocale();
  const router = useRouter();
  const [, startTransition] = useTransition();

  const initial = user.email.slice(0, 1).toUpperCase();

  function switchLocale(next: string) {
    startTransition(async () => {
      await setLocale(next);
      router.refresh();
    });
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger aria-label={t("account_and_settings")} className="rounded-full">
        <Avatar>
          <AvatarFallback>{initial}</AvatarFallback>
        </Avatar>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-64">
        <DropdownMenuLabel className="truncate font-normal">
          <span className="block truncate text-sm font-medium">{user.email}</span>
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem asChild>
          <Link href="/account">
            <User /> {t("my_account")}
          </Link>
        </DropdownMenuItem>
        <DropdownMenuItem asChild>
          <Link href="/account/api-keys">
            <KeyRound /> {t("my_api_keys")}
          </Link>
        </DropdownMenuItem>
        {whatsNewEnabled && (
          <DropdownMenuItem asChild>
            <Link href="/whats-new">
              <Sparkles /> {t("whats_new")}
              {hasUnseen && (
                <>
                  <span aria-hidden="true" className="bg-success ml-auto size-2 rounded-full" />
                  <span className="sr-only">{t("whats_new_unseen")}</span>
                </>
              )}
            </Link>
          </DropdownMenuItem>
        )}
        <DropdownMenuItem asChild>
          <Link href="/account/integrations">
            <Building2 /> {t("integrations")}
          </Link>
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuSub>
          <DropdownMenuSubTrigger>
            <Globe className="text-muted-foreground mr-2 size-4" /> {t("language")}
          </DropdownMenuSubTrigger>
          <DropdownMenuSubContent>
            <DropdownMenuRadioGroup value={locale} onValueChange={switchLocale}>
              {locales.map((value) => (
                <DropdownMenuRadioItem key={value} value={value}>
                  {LOCALE_LABELS[value] ?? value}
                </DropdownMenuRadioItem>
              ))}
            </DropdownMenuRadioGroup>
          </DropdownMenuSubContent>
        </DropdownMenuSub>
        <DropdownMenuSeparator />
        {federationStatus.has_multi_tenant_federation && (
          <DropdownMenuItem asChild>
            <a href="/login/switch-organisation">
              <Building2 /> {t("oidc_choose_another_org")}
            </a>
          </DropdownMenuItem>
        )}
        <DropdownMenuItem variant="destructive" asChild>
          <a href="/logout">
            <LogOut /> {t("logout")}
          </a>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// frontend/apps/web/src/routes/(app)/ProfileMenu.svelte
<script lang="ts">
  import { User, KeyRound, Building2, LogOut, Sparkles } from "lucide-svelte";
  import * as DropdownMenu from "$lib/components/ui/dropdown-menu/index.js";
  import ThemeToggle from "$lib/components/ThemeToggle.svelte";
  import { m } from "$lib/paraglide/messages";
  import { localizeHref } from "$lib/paraglide/runtime";
  import { goto } from "$app/navigation";
  import { browser } from "$app/environment";
  import { getAppContext } from "$lib/core/AppContext";
  import { getWhatsNewStore } from "$lib/features/whats-new/whatsNewStore";

  interface Props {
    tenantFederationEnabled?: boolean;
  }

  const { tenantFederationEnabled = false }: Props = $props();

  const {
    user,
    state: { userInfo }
  } = getAppContext();
  const { hasUnseen, enabled: whatsNewEnabled } = getWhatsNewStore();

  const displayName = $derived(
    $userInfo.displayName?.trim() || `${$userInfo.firstName} ${$userInfo.lastName}`.trim()
  );
  const initials = $derived(
    displayName
      .split(/\s+/)
      .filter(Boolean)
      .slice(0, 2)
      .map((word) => word[0]?.toUpperCase() ?? "")
      .join("") || "?"
  );

  function handleSwitchOrganisation() {
    // Clear client-side tenant storage
    if (browser) {
      sessionStorage.removeItem("eneo-last-tenant-slug");
      localStorage.removeItem("eneo:last-tenant");
    }

    // Navigate to endpoint (not a SvelteKit route — server endpoint)
    // eslint-disable-next-line svelte/no-navigation-without-resolve -- server endpoint, not a typed route
    goto("/login/switch-organisation");
  }
</script>

<DropdownMenu.Root>
  <DropdownMenu.Trigger>
    {#snippet child({ props })}
      <button
        {...props}
        type="button"
        aria-label={$hasUnseen
          ? `${m.account_and_settings()} – ${m.whats_new_unseen()}`
          : m.account_and_settings()}
        class="bg-accent-default text-on-fill hover:bg-accent-stronger focus-visible:ring-ring/50 relative flex size-9 shrink-0 items-center justify-center rounded-full text-sm font-semibold transition-colors focus-visible:ring-3 focus-visible:outline-none"
      >
        {initials}
        {#if $hasUnseen}
          <span
            aria-hidden="true"
            class="bg-positive-default ring-secondary absolute -top-0.5 -right-0.5 size-3 rounded-full ring-2"
          ></span>
        {/if}
      </button>
    {/snippet}
  </DropdownMenu.Trigger>

  <DropdownMenu.Content align="end" class="w-64">
    <div class="flex flex-col px-2 py-1.5">
      <span class="text-foreground truncate text-sm font-medium">{displayName}</span>
      <span class="text-muted truncate text-xs">{user.email}</span>
    </div>

    <DropdownMenu.Separator />

    <!-- eslint-disable svelte/no-navigation-without-resolve -- localizeHref handles routing -->
    <DropdownMenu.Item>
      {#snippet child({ props })}
        <a {...props} href={localizeHref("/account")}>
          <User />
          {m.my_account()}
        </a>
      {/snippet}
    </DropdownMenu.Item>

    <DropdownMenu.Item>
      {#snippet child({ props })}
        <a {...props} href={localizeHref("/account/api-keys")}>
          <KeyRound />
          {m.my_api_keys()}
        </a>
      {/snippet}
    </DropdownMenu.Item>

    {#if whatsNewEnabled}
      <DropdownMenu.Item>
        {#snippet child({ props })}
          <a {...props} href={localizeHref("/whats-new")}>
            <Sparkles />
            {m.whats_new()}
            {#if $hasUnseen}
              <span aria-hidden="true" class="bg-positive-default ml-auto size-2 rounded-full"
              ></span>
              <span class="sr-only">{m.whats_new_unseen()}</span>
            {/if}
          </a>
        {/snippet}
      </DropdownMenu.Item>
    {/if}
    <!-- eslint-enable svelte/no-navigation-without-resolve -->

    {#if tenantFederationEnabled}
      <DropdownMenu.Item onclick={handleSwitchOrganisation}>
        <Building2 />
        {m.oidc_choose_another_org()}
      </DropdownMenu.Item>
    {/if}

    <DropdownMenu.Separator />

    <div class="flex items-center justify-between gap-2 px-2 py-1.5">
      <span class="text-foreground text-sm">{m.theme()}</span>
      <ThemeToggle menu />
    </div>

    <DropdownMenu.Separator />

    <!-- eslint-disable svelte/no-navigation-without-resolve -- localizeHref handles routing -->
    <DropdownMenu.Item variant="destructive">
      {#snippet child({ props })}
        <!-- The logout load clears the session cookies, so hover preloading
             must not run it (hover is enabled on the (app) layout wrapper). -->
        <a {...props} href={localizeHref("/logout")} data-sveltekit-preload-data="false">
          <LogOut />
          {m.logout()}
        </a>
      {/snippet}
    </DropdownMenu.Item>
    <!-- eslint-enable svelte/no-navigation-without-resolve -->
  </DropdownMenu.Content>
</DropdownMenu.Root>
