// frontend/apps/web/src/lib/features/integrations/sharepoint/SharePointAppConfigDialog.svelte
<script lang="ts">
  import { createAsyncState } from "$lib/core/helpers/createAsyncState.svelte";
  import { getIntric } from "$lib/core/Intric";
  import { IconLoadingSpinner } from "@intric/icons/loading-spinner";
  import { getErrorMessage, toastError } from "$lib/core/errors";
  import { Button, Dialog, Input } from "@intric/ui";
  import { m } from "$lib/paraglide/messages";
  import { toast } from "$lib/components/toast";
  import { writable, type Writable } from "svelte/store";
  import { AlertTriangle } from "lucide-svelte";
  import SharePointAppDeleteDialog from "./SharePointAppDeleteDialog.svelte";

  // Types for SharePoint app configuration (until OpenAPI types are regenerated)
  type TenantSharePointAppCreate = {
    client_id: string;
    client_secret: string;
    tenant_domain: string;
    certificate_path?: string | null;
  };

  type TenantSharePointAppPublic = {
    id: string;
    tenant_id: string;
    client_id: string;
    client_secret_masked: string;
    tenant_domain: string;
    is_active: boolean;
    auth_method: "tenant_app" | "service_account";
    service_account_email?: string | null;
    certificate_path?: string | null;
    created_by?: string | null;
    created_at: string;
    updated_at: string;
  };

  type TenantAppTestResult = {
    success: boolean;
    error_message?: string | null;
    details?: string | null;
  };

  type ServiceAccountAuthStartResponse = {
    auth_url: string;
    state: string;
  };

  type AuthMethod = "tenant_app" | "service_account";

  let { openController }: { openController: Writable<boolean> } = $props();

  const intric = getIntric();

  // Form state
  let authMethod = $state<AuthMethod>("service_account"); // Default to recommended
  let clientId = $state("");
  let clientSecret = $state("");
  let tenantDomain = $state("");
  let existingConfig = $state<TenantSharePointAppPublic | null>(null);
  let testResult = $state<TenantAppTestResult | null>(null);
  let oauthState = $state<string | null>(null);
  let isOAuthInProgress = $state(false);
  const deleteDialogOpen = writable(false);
  let isUpdatingSecret = $state(false);
  let newClientSecret = $state("");

  // Load existing configuration
  const loadConfig = createAsyncState(async () => {
    try {
      const data = await intric.client.fetch("/api/v1/admin/sharepoint/app", {
        method: "get",
        params: {}
      });

      if (data) {
        existingConfig = data as TenantSharePointAppPublic;
        clientId = data.client_id;
        tenantDomain = data.tenant_domain;
        authMethod = data.auth_method || "tenant_app";
        // Don't populate secret - require user to re-enter if updating
      }
    } catch (error) {
      console.error("Failed to load SharePoint app config:", error);
    }
  });

  // Test credentials
  const testCredentials = createAsyncState(async () => {
    testResult = null;

    if (!clientId || !clientSecret || !tenantDomain) {
      toast.warning(m.fill_required_fields());
      return;
    }

    try {
      const payload: TenantSharePointAppCreate = {
        client_id: clientId,
        client_secret: clientSecret,
        tenant_domain: tenantDomain,
      };

      const result = await intric.client.fetch("/api/v1/admin/sharepoint/app/test", {
        method: "post",
        params: {},
        requestBody: {
          "application/json": payload
        }
      }) as TenantAppTestResult;

      testResult = result;

        if (!result.success) {
          toast.error(
          m.connection_test_failed({ message: result.error_message || m.unknown_error() })
          );
        }
    } catch (error) {
      toastError(error);
      testResult = {
        success: false,
        error_message: getErrorMessage(error),
      };
    }
  });

  // Save configuration
  const saveConfig = createAsyncState(async () => {
    if (!clientId || !clientSecret || !tenantDomain) {
      toast.warning(m.fill_required_fields());
      return;
    }

    try {
      const payload: TenantSharePointAppCreate = {
        client_id: clientId,
        client_secret: clientSecret,
        tenant_domain: tenantDomain,
      };

      const result = await intric.client.fetch("/api/v1/admin/sharepoint/app", {
        method: "post",
        params: {},
        requestBody: {
          "application/json": payload
        }
      }) as TenantSharePointAppPublic;

      existingConfig = result;
      $openController = false;
    } catch (error) {
      toastError(error);
    }
  });

  // Update client secret only
  const updateSecret = createAsyncState(async () => {
    if (!existingConfig || !newClientSecret) {
      toast.warning(m.fill_required_fields());
      return;
    }

    try {
      const payload: TenantSharePointAppCreate = {
        client_id: existingConfig.client_id,
        client_secret: newClientSecret,
        tenant_domain: existingConfig.tenant_domain,
      };

      const result = await intric.client.fetch("/api/v1/admin/sharepoint/app", {
        method: "post",
        params: {},
        requestBody: {
          "application/json": payload
        }
      }) as TenantSharePointAppPublic;

      existingConfig = result;
      isUpdatingSecret = false;
      newClientSecret = "";
    } catch (error) {
      toastError(error);
    }
  });

  // Start service account OAuth flow
  const startServiceAccountOAuth = createAsyncState(async () => {
    if (!clientId || !clientSecret || !tenantDomain) {
      toast.warning(m.fill_required_fields());
      return;
    }

    try {
      const payload = {
        client_id: clientId,
        client_secret: clientSecret,
        tenant_domain: tenantDomain,
      };

      const result = await intric.client.fetch("/api/v1/admin/sharepoint/service-account/auth/start", {
        method: "post",
        params: {},
        requestBody: {
          "application/json": payload
        }
      }) as ServiceAccountAuthStartResponse;

      // Store state for callback verification
      oauthState = result.state;
      isOAuthInProgress = true;

      // Store state in sessionStorage for callback verification
      sessionStorage.setItem("sharepoint_service_account_oauth", JSON.stringify({
        state: result.state,
      }));

      // Redirect to Microsoft OAuth
      window.location.href = result.auth_url;
    } catch (error) {
      toastError(error);
    }
  });

  // Load config when dialog opens
  $effect(() => {
    if ($openController) {
      loadConfig();
    }
  });

  // Reset state when dialog closes
  $effect(() => {
    if (!$openController) {
      existingConfig = null;
      clientId = "";
      clientSecret = "";
      tenantDomain = "";
      testResult = null;
      authMethod = "service_account";
      isUpdatingSecret = false;
      newClientSecret = "";
    }
  });
</script>

<Dialog.Root {openController}>
  <Dialog.Content width="medium">
    <Dialog.Title>{m.configure_sharepoint_app_title()}</Dialog.Title>

    <Dialog.Section scrollable={true}>
      {#if loadConfig.isLoading}
        <div class="flex items-center justify-center gap-2 p-8">
          <IconLoadingSpinner class="animate-spin" />
          <span class="text-secondary">{m.loading_configuration()}</span>
        </div>
      {:else if existingConfig}
        <!-- Read-only view when integration exists -->
        <div class="space-y-4 p-4">
          <div class="rounded-md border border-default bg-secondary p-4">
            <div class="text-sm font-medium text-primary mb-3">{m.current_configuration()}</div>
            <div class="space-y-2 text-sm text-secondary">
              <div>
                <span class="font-medium">{m.auth_method()}:</span>
                {existingConfig.auth_method === "service_account"
                  ? m.service_account_option()
                  : m.tenant_app_option()}
              </div>
              <div>
                <span class="font-medium">{m.client_id()}:</span>
                {existingConfig.client_id}
              </div>
              <div>
                <span class="font-medium">{m.secret()}:</span>
                {existingConfig.client_secret_masked}
              </div>
              <div>
                <span class="font-medium">{m.domain()}:</span>
                {existingConfig.tenant_domain}
              </div>
              {#if existingConfig.service_account_email}
                <div>
                  <span class="font-medium">{m.service_account_email()}:</span>
                  {existingConfig.service_account_email}
                </div>
              {/if}
              <div>
                <span class="font-medium">{m.status()}:</span>
                <span class={existingConfig.is_active ? "text-positive-default" : "text-negative-default"}>
                  {existingConfig.is_active ? m.active() : m.inactive()}
                </span>
              </div>
            </div>
          </div>

          {#if isUpdatingSecret}
            <!-- Update secret form -->
            <div class="rounded-md border border-accent-default bg-accent-dimmer p-4">
              <div class="text-sm font-medium text-accent-stronger mb-3">{m.update_client_secret()}</div>
                <Input.Text
                  label={m.new_client_secret()}
                  bind:value={newClientSecret}
                  required
                  type="password"
                  placeholder={m.enter_new_client_secret()}
                  description={m.new_client_secret_description()}
                  autocomplete="off"
                />
            </div>
          {:else}
            <!-- Warning about changing auth method -->
            <div class="rounded-lg border border-warning-default bg-warning-dimmer px-4 py-3">
              <div class="flex items-start gap-3">
                <AlertTriangle class="text-warning-stronger shrink-0 mt-0.5" size={18} />
                <p class="text-sm text-warning-stronger">
                  {m.sharepoint_change_auth_warning()}
                </p>
              </div>
            </div>
          {/if}
        </div>
      {:else}
        <!-- Configuration form for new setup -->
        <div class="space-y-4 p-4">
          <!-- Auth Method Selector -->
          <div class="space-y-3">
            <div class="text-sm font-medium text-primary">
              {m.choose_auth_method()}
            </div>

            <!-- Service Account (Recommended) -->
            <label
              class="flex cursor-pointer items-start gap-3 rounded-lg border p-4 transition-colors
                {authMethod === 'service_account'
                  ? 'border-accent-default bg-accent-dimmer'
                  : 'border-default hover:border-stronger'}"
            >
              <input
                type="radio"
                name="auth_method"
                value="service_account"
                bind:group={authMethod}
                class="mt-1"
              />
              <div class="flex-1">
                <div class="flex items-center gap-2">
                  <span class="font-medium text-primary">
                    {m.service_account_option()}
                  </span>
                  <span class="rounded bg-accent-dimmer px-2 py-0.5 text-xs font-medium text-accent-stronger">
                    {m.recommended()}
                  </span>
                </div>
                <p class="mt-1 text-sm text-secondary">
                  {m.service_account_description()}
                </p>
              </div>
            </label>

            <!-- Tenant App -->
            <label
              class="flex cursor-pointer items-start gap-3 rounded-lg border p-4 transition-colors
                {authMethod === 'tenant_app'
                  ? 'border-accent-default bg-accent-dimmer'
                  : 'border-default hover:border-stronger'}"
            >
              <input
                type="radio"
                name="auth_method"
                value="tenant_app"
                bind:group={authMethod}
                class="mt-1"
              />
              <div class="flex-1">
                <span class="font-medium text-primary">
                  {m.tenant_app_option()}
                </span>
                <p class="mt-1 text-sm text-secondary">
                  {m.tenant_app_description()}
                </p>
              </div>
            </label>
          </div>

          <hr class="my-4 border-default" />

          <!-- Credentials Form (same for both) -->
          <p class="text-sm text-secondary">
            {m.sharepoint_app_config_description()}
          </p>

          <Input.Text
            label={m.client_id()}
            bind:value={clientId}
            required
            placeholder="12345678-1234-1234-1234-123456789012"
            description={m.client_id_description()}
            autocomplete="off"
          />

          <Input.Text
            label={m.client_secret()}
            bind:value={clientSecret}
            required
            type="password"
            placeholder="Enter client secret"
            description={m.client_secret_description()}
            autocomplete="off"
          />

          <Input.Text
            label={m.tenant_id_or_domain()}
            bind:value={tenantDomain}
            required
            placeholder="contoso.onmicrosoft.com"
            description={m.tenant_id_or_domain_description()}
            autocomplete="off"
          />

          {#if testResult}
            <div
              class="rounded-md border p-3 {testResult.success
                ? 'border-positive-default bg-positive-dimmer text-positive-stronger'
                : 'border-negative-default bg-negative-dimmer text-negative-stronger'}"
            >
              <div class="text-sm font-medium">
                {testResult.success ? m.connection_successful() : m.connection_failed()}
              </div>
              {#if testResult.error_message}
                <div class="mt-1 text-xs">{testResult.error_message}</div>
              {/if}
              {#if testResult.details}
                <div class="mt-1 text-xs">{testResult.details}</div>
              {/if}
            </div>
          {/if}
        </div>
      {/if}
    </Dialog.Section>

    <Dialog.Controls>
      <Button
        onclick={() => {
          $openController = false;
        }}>{m.cancel()}</Button
      >

      {#if existingConfig && isUpdatingSecret}
        <!-- Update secret mode buttons -->
        <Button
          variant="secondary"
          onclick={() => {
            isUpdatingSecret = false;
            newClientSecret = "";
          }}
        >
          {m.back()}
        </Button>
        <Button
          variant="primary"
          disabled={updateSecret.isLoading || !newClientSecret}
          onclick={updateSecret}
        >
          {updateSecret.isLoading ? m.saving() : m.save()}
        </Button>
      {:else if existingConfig}
        <!-- Normal view buttons when config exists -->
        <Button
          variant="secondary"
          onclick={() => {
            isUpdatingSecret = true;
          }}
        >
          {m.update_secret()}
        </Button>
        <Button
          variant="destructive"
          onclick={() => {
            $deleteDialogOpen = true;
          }}
        >
          {m.delete_sharepoint_app()}
        </Button>
      {:else if authMethod === "tenant_app"}
        <!-- Tenant App: Test + Save flow -->
        <Button
          variant="secondary"
          disabled={testCredentials.isLoading ||
            !clientId ||
            !clientSecret ||
            !tenantDomain}
          onclick={testCredentials}
        >
          {testCredentials.isLoading ? m.testing() : m.test_connection()}
        </Button>
        <Button
          variant="primary"
          disabled={saveConfig.isLoading ||
            !clientId ||
            !clientSecret ||
            !tenantDomain}
          onclick={saveConfig}
        >
          {saveConfig.isLoading ? m.saving() : m.save()}
        </Button>
      {:else}
        <!-- Service Account: Sign in with Microsoft -->
        <Button
          variant="primary"
          disabled={startServiceAccountOAuth.isLoading ||
            !clientId ||
            !clientSecret ||
            !tenantDomain}
          onclick={startServiceAccountOAuth}
        >
          {startServiceAccountOAuth.isLoading
            ? m.redirecting()
            : m.sign_in_with_microsoft()}
        </Button>
      {/if}
    </Dialog.Controls>
  </Dialog.Content>
</Dialog.Root>

<SharePointAppDeleteDialog openController={deleteDialogOpen} />

// frontend/apps/web-next/src/features/admin/integrations/sharepoint-app-config-dialog.tsx
"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useTranslations } from "next-intl";
import { useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { browserApi } from "@/lib/api/browser";
import { unwrap } from "@/lib/api/errors";
import { toastApiError } from "@/lib/api/toast";
import { SHAREPOINT_APP_KEY, sharepointAppQueryOptions } from "./integrations";

type AuthMethod = "service_account" | "tenant_app";
const OAUTH_STATE_KEY = "sharepoint_service_account_oauth";

export function SharePointAppConfigDialog({
  open,
  onOpenChange,
  onRequestDelete
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onRequestDelete: () => void;
}) {
  const t = useTranslations();
  const queryClient = useQueryClient();
  const { data: config, isPending } = useQuery({
    ...sharepointAppQueryOptions(browserApi),
    enabled: open
  });

  const [authMethod, setAuthMethod] = useState<AuthMethod>("service_account");
  const [clientId, setClientId] = useState("");
  const [clientSecret, setClientSecret] = useState("");
  const [tenantDomain, setTenantDomain] = useState("");
  const [updatingSecret, setUpdatingSecret] = useState(false);
  const [testResult, setTestResult] = useState<{ ok: boolean; message?: string } | null>(null);

  const invalidate = () => queryClient.invalidateQueries({ queryKey: SHAREPOINT_APP_KEY });
  const requireFields = () => {
    if (!clientId.trim() || !clientSecret.trim() || !tenantDomain.trim()) {
      toast.warning(t("fill_required_fields"));
      return false;
    }
    return true;
  };

  const test = useMutation({
    mutationFn: () =>
      unwrap(
        browserApi.POST("/api/v1/admin/sharepoint/app/test", {
          body: {
            client_id: clientId.trim(),
            client_secret: clientSecret,
            tenant_domain: tenantDomain.trim()
          }
        })
      ),
    onSuccess: (result) =>
      setTestResult({ ok: result.success, message: result.error_message ?? result.details ?? "" }),
    onError: (error) => toastApiError(error, t)
  });

  const save = useMutation({
    mutationFn: (body: { client_id: string; client_secret: string; tenant_domain: string }) =>
      unwrap(browserApi.POST("/api/v1/admin/sharepoint/app", { body })),
    onSuccess: () => {
      toast.success(t("sharepoint_app_configured_successfully"));
      void invalidate();
      setUpdatingSecret(false);
      onOpenChange(false);
    },
    onError: (error) => toastApiError(error, t)
  });

  const startOAuth = useMutation({
    mutationFn: () =>
      unwrap(
        browserApi.POST("/api/v1/admin/sharepoint/service-account/auth/start", {
          body: {
            client_id: clientId.trim(),
            client_secret: clientSecret,
            tenant_domain: tenantDomain.trim()
          }
        })
      ),
    onSuccess: ({ auth_url, state }) => {
      sessionStorage.setItem(OAUTH_STATE_KEY, JSON.stringify({ state }));
      window.location.href = auth_url;
    },
    onError: (error) => toastApiError(error, t)
  });

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>{t("configure_sharepoint_app_title")}</DialogTitle>
          <DialogDescription>{t("sharepoint_app_config_description")}</DialogDescription>
        </DialogHeader>

        {isPending ? (
          <Skeleton className="h-40 w-full" />
        ) : config ? (
          <div className="flex flex-col gap-3">
            <div className="flex flex-col gap-2 rounded-lg border p-3 text-sm">
              <span className="font-medium">{t("current_configuration")}</span>
              <Field label={t("service_account_option")} value={config.auth_method} />
              <Field label={t("client_id")} value={config.client_id} mono />
              <Field label={t("client_secret")} value={config.client_secret_masked} mono />
              <Field label={t("tenant_id_or_domain")} value={config.tenant_domain} />
              {config.service_account_email && (
                <Field label={t("service_account_option")} value={config.service_account_email} />
              )}
              <Badge variant={config.is_active ? "default" : "secondary"} className="w-fit">
                {config.is_active ? t("active") : t("inactive")}
              </Badge>
            </div>
            {updatingSecret ? (
              <div className="flex flex-col gap-2">
                <Label htmlFor="sp-new-secret">{t("new_client_secret")}</Label>
                <Input
                  id="sp-new-secret"
                  type="password"
                  autoComplete="off"
                  value={clientSecret}
                  onChange={(event) => setClientSecret(event.target.value)}
                />
              </div>
            ) : (
              <p className="text-muted-foreground text-xs">{t("sharepoint_change_auth_warning")}</p>
            )}
          </div>
        ) : (
          <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-2">
              <Label>{t("service_account_option")}</Label>
              <Select value={authMethod} onValueChange={(v) => setAuthMethod(v as AuthMethod)}>
                <SelectTrigger className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="service_account">
                    {t("service_account_option")} · {t("recommended")}
                  </SelectItem>
                  <SelectItem value="tenant_app">{t("tenant_app_option")}</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Labeled label={t("client_id")}>
              <Input value={clientId} onChange={(event) => setClientId(event.target.value)} />
            </Labeled>
            <Labeled label={t("client_secret")}>
              <Input
                type="password"
                autoComplete="off"
                value={clientSecret}
                onChange={(event) => setClientSecret(event.target.value)}
              />
            </Labeled>
            <Labeled label={t("tenant_id_or_domain")}>
              <Input
                placeholder={t("sharepoint_tenant_domain_placeholder")}
                value={tenantDomain}
                onChange={(event) => setTenantDomain(event.target.value)}
              />
            </Labeled>
            {testResult && (
              <p
                className={
                  testResult.ok
                    ? "rounded-md border border-green-200 bg-green-50 px-3 py-2 text-sm text-green-700 dark:border-green-900 dark:bg-green-950 dark:text-green-400"
                    : "rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700 dark:border-red-900 dark:bg-red-950 dark:text-red-400"
                }
              >
                {testResult.ok ? t("connection_successful") : t("connection_failed")}
                {testResult.message ? ` — ${testResult.message}` : ""}
              </p>
            )}
          </div>
        )}

        <DialogFooter className="flex-wrap gap-2">
          {config ? (
            updatingSecret ? (
              <>
                <Button variant="outline" onClick={() => setUpdatingSecret(false)}>
                  {t("back")}
                </Button>
                <Button
                  disabled={!clientSecret || save.isPending}
                  onClick={() =>
                    save.mutate({
                      client_id: config.client_id,
                      client_secret: clientSecret,
                      tenant_domain: config.tenant_domain
                    })
                  }
                >
                  {t("save")}
                </Button>
              </>
            ) : (
              <>
                <Button variant="outline" onClick={() => setUpdatingSecret(true)}>
                  {t("update_secret")}
                </Button>
                <Button variant="destructive" onClick={onRequestDelete}>
                  {t("delete_sharepoint_app")}
                </Button>
              </>
            )
          ) : authMethod === "tenant_app" ? (
            <>
              <Button
                variant="outline"
                disabled={test.isPending}
                onClick={() => requireFields() && test.mutate()}
              >
                {test.isPending ? t("testing_connection") : t("test_connection")}
              </Button>
              <Button
                disabled={save.isPending}
                onClick={() =>
                  requireFields() &&
                  save.mutate({
                    client_id: clientId.trim(),
                    client_secret: clientSecret,
                    tenant_domain: tenantDomain.trim()
                  })
                }
              >
                {t("save")}
              </Button>
            </>
          ) : (
            <Button
              disabled={startOAuth.isPending}
              onClick={() => requireFields() && startOAuth.mutate()}
            >
              {t("sign_in_with_microsoft")}
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function Labeled({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-2">
      <Label>{label}</Label>
      {children}
    </div>
  );
}

function Field({ label, value, mono }: { label: string; value?: string | null; mono?: boolean }) {
  return (
    <div className="flex items-center justify-between gap-2">
      <span className="text-muted-foreground text-xs">{label}</span>
      <span className={mono ? "font-mono text-xs" : "text-xs"}>{value || "—"}</span>
    </div>
  );
}
