// frontend/apps/web/src/lib/features/integrations/sharepoint/SharePointAppDeleteDialog.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { Writable } from "svelte/store";
  import { AlertTriangle, LoaderCircle } from "lucide-svelte";
  import * as AlertDialog from "$lib/components/ui/alert-dialog/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import * as Field from "$lib/components/ui/field/index.js";
  import { Input } from "$lib/components/ui/input/index.js";
  import { getEneo } from "$lib/core/Eneo";
  import { toastError } from "$lib/core/errors";
  import { m } from "$lib/paraglide/messages";
  import { toast } from "$lib/components/toast";

  let {
    openController,
    onDeleted
  }: {
    openController: Writable<boolean>;
    onDeleted?: () => void;
  } = $props();

  const eneo = getEneo();

  let dialogOpen = $state(false);
  onMount(() => openController.subscribe((value) => (dialogOpen = value)));
  $effect(() => {
    openController.set(dialogOpen);
  });

  let isDeleting = $state(false);
  let confirmationText = $state("");
  const confirmationWord = m.sharepoint_delete_confirmation_word();

  let isConfirmed = $derived(
    confirmationText.trim().toUpperCase() === confirmationWord.toUpperCase()
  );

  async function handleDelete() {
    if (!isConfirmed || isDeleting) return;
    isDeleting = true;

    try {
      await eneo.client.fetch("/api/v1/admin/sharepoint/app", { method: "delete" });
      toast.success(m.sharepoint_app_deleted());
      dialogOpen = false;
      onDeleted?.();
    } catch (error) {
      toastError(error, m.failed_to_delete_sharepoint_app());
    } finally {
      isDeleting = false;
    }
  }

  $effect(() => {
    if (!dialogOpen) confirmationText = "";
  });
</script>

<AlertDialog.Root bind:open={dialogOpen}>
  <AlertDialog.Content>
    <AlertDialog.Header>
      <AlertDialog.Title>{m.delete_sharepoint_app()}</AlertDialog.Title>
      <AlertDialog.Description>
        {m.delete_sharepoint_app_warning()}
      </AlertDialog.Description>
    </AlertDialog.Header>

    <div class="border-destructive/40 bg-destructive/10 rounded-lg border px-4 py-3">
      <div class="flex items-start gap-3">
        <AlertTriangle class="text-destructive mt-0.5 size-4 shrink-0" aria-hidden="true" />
        <div class="flex flex-col gap-2 text-sm">
          <p class="font-semibold">{m.warning_permanent_deletion()}</p>
          <ul class="text-muted-foreground list-inside list-disc space-y-1">
            <li>{m.sharepoint_delete_warning_knowledge()}</li>
            <li>{m.sharepoint_delete_warning_assistants()}</li>
            <li>{m.sharepoint_delete_warning_webhooks()}</li>
            <li>{m.sharepoint_delete_warning_tokens()}</li>
          </ul>
          <p class="text-destructive font-medium">{m.this_cannot_be_undone()}</p>
        </div>
      </div>
    </div>

    <Field.Field>
      <Field.Label for="sharepoint-confirm-delete">
        {m.type_to_confirm({ word: confirmationWord })}
      </Field.Label>
      <Input
        id="sharepoint-confirm-delete"
        bind:value={confirmationText}
        placeholder={confirmationWord}
        autocomplete="off"
        autocorrect="off"
        spellcheck={false}
      />
    </Field.Field>

    <AlertDialog.Footer>
      <AlertDialog.Cancel disabled={isDeleting}>{m.cancel()}</AlertDialog.Cancel>
      <Button variant="destructive" onclick={handleDelete} disabled={!isConfirmed || isDeleting}>
        {#if isDeleting}
          <LoaderCircle class="animate-spin" aria-hidden="true" />
        {/if}
        {isDeleting ? m.deleting() : m.permanent_delete()}
      </Button>
    </AlertDialog.Footer>
  </AlertDialog.Content>
</AlertDialog.Root>

// frontend/apps/web-next/src/features/admin/integrations/sharepoint-app-delete-dialog.tsx
"use client";

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle } from "lucide-react";
import { useTranslations } from "next-intl";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { browserApi } from "@/lib/api/browser";
import { unwrap } from "@/lib/api/errors";
import { toastApiError } from "@/lib/api/toast";
import { toast } from "@/lib/toast";
import {
  SHAREPOINT_APP_KEY,
  SHAREPOINT_SUBSCRIPTIONS_KEY,
  TENANT_INTEGRATIONS_KEY
} from "./integrations";

const CONFIRM_WORD = "DELETE";

export function SharePointAppDeleteDialog({
  open,
  onOpenChange
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const t = useTranslations();
  const queryClient = useQueryClient();
  const [confirm, setConfirm] = useState("");

  const remove = useMutation({
    mutationFn: () => unwrap(browserApi.DELETE("/api/v1/admin/sharepoint/app")),
    onSuccess: () => {
      toast.success(t("sharepoint_app_deleted_successfully"));
      for (const key of [SHAREPOINT_APP_KEY, SHAREPOINT_SUBSCRIPTIONS_KEY, TENANT_INTEGRATIONS_KEY])
        void queryClient.invalidateQueries({ queryKey: key });
      setConfirm("");
      onOpenChange(false);
    },
    onError: (error) => toastApiError(error, t)
  });

  const confirmed = confirm.trim().toUpperCase() === CONFIRM_WORD;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("delete_sharepoint_app")}</DialogTitle>
        </DialogHeader>
        <div className="flex flex-col gap-3">
          <div className="border-destructive/30 bg-destructive/10 text-destructive flex flex-col gap-2 rounded-lg border px-3 py-2 text-sm">
            <span className="flex items-center gap-2 font-medium">
              <AlertTriangle className="size-4" /> {t("delete_sharepoint_app_warning")}
            </span>
            <ul className="ml-6 list-disc text-xs">
              <li>{t("sharepoint_delete_warning_knowledge")}</li>
              <li>{t("sharepoint_delete_warning_assistants")}</li>
              <li>{t("sharepoint_delete_warning_webhooks")}</li>
              <li>{t("sharepoint_delete_warning_tokens")}</li>
            </ul>
            <span className="font-semibold">{t("this_cannot_be_undone")}</span>
          </div>
          <Input
            value={confirm}
            placeholder={t("type_to_confirm", { word: CONFIRM_WORD })}
            onChange={(event) => setConfirm(event.target.value)}
          />
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            {t("cancel")}
          </Button>
          <Button
            variant="destructive"
            disabled={!confirmed || remove.isPending}
            onClick={() => remove.mutate()}
          >
            {remove.isPending ? t("deleting") : t("permanent_delete")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
