// frontend/apps/web-next/src/features/admin/governance/prompt-enforcement-section.tsx
"use client";

import { AlertCircle, Info, Sparkles } from "lucide-react";
import { useTranslations } from "next-intl";
import Link from "next/link";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Switch } from "@/components/ui/switch";
import { PolicySection } from "./policy-section";
import type { PolicyDraft } from "./use-policy-draft";

export function PromptEnforcementSection({ draft }: { draft: PolicyDraft }) {
  const t = useTranslations();
  const {
    promptEnabled,
    setPromptEnabled,
    selectedPromptId,
    setSelectedPromptId,
    promptOptions,
    promptSummary,
    badgeVariant
  } = draft;

  return (
    <PolicySection
      id="prompt"
      title={t("governance_prompt_heading")}
      description={t("governance_prompt_section_desc")}
      summary={promptSummary}
      summaryVariant={badgeVariant(promptEnabled, selectedPromptId !== null)}
      icon={<Sparkles className="size-5" />}
    >
      <div className="flex items-center justify-between gap-3">
        <Label htmlFor="prompt-enabled" className="text-sm font-medium">
          {t("governance_prompt_toggle_label")}
        </Label>
        <Switch
          id="prompt-enabled"
          checked={promptEnabled}
          onCheckedChange={setPromptEnabled}
          aria-describedby="prompt-help"
        />
      </div>

      {!promptEnabled ? (
        <p id="prompt-help" className="text-muted-foreground text-sm">
          {t("governance_prompt_help_disabled")}
        </p>
      ) : promptOptions.length === 0 ? (
        <Alert>
          <Info className="size-4" />
          <AlertDescription className="text-muted-foreground">
            {t("governance_prompt_library_empty")}
            <Link className="text-primary mt-1 inline-block underline" href="/admin/prompt-library">
              {t("governance_prompt_create_in_library")}
            </Link>
          </AlertDescription>
        </Alert>
      ) : (
        <>
          <p id="prompt-help" className="text-muted-foreground text-sm">
            {t("governance_prompt_help_enabled")}
          </p>
          <RadioGroup
            value={selectedPromptId ?? ""}
            onValueChange={(value) => setSelectedPromptId(value)}
          >
            <div className="space-y-2">
              {promptOptions.map((prompt) => (
                <Label
                  key={prompt.id}
                  htmlFor={`prompt-${prompt.id}`}
                  className={`flex cursor-pointer items-start gap-3 rounded-lg border p-3 transition-colors ${
                    selectedPromptId === prompt.id ? "border-primary" : "hover:border-foreground/30"
                  }`}
                >
                  <RadioGroupItem value={prompt.id} id={`prompt-${prompt.id}`} className="mt-0.5" />
                  <div className="flex-1">
                    <div className="text-sm font-medium">{prompt.name}</div>
                    {prompt.description && (
                      <div className="text-muted-foreground mt-0.5 text-xs">
                        {prompt.description}
                      </div>
                    )}
                  </div>
                </Label>
              ))}
            </div>
          </RadioGroup>
          {!selectedPromptId && (
            <p className="text-destructive flex items-center gap-2 text-sm" role="alert">
              <AlertCircle className="size-4 shrink-0" aria-hidden="true" />
              {t("governance_prompt_error_required")}
            </p>
          )}
        </>
      )}
    </PolicySection>
  );
}

// frontend/apps/web/src/routes/(app)/admin/personal-assistant/configuration/PromptEnforcementSection.svelte
<!--
    Copyright (c) 2026 Sundsvalls Kommun

    Licensed under the MIT License.
-->

<script lang="ts">
  import { resolve } from "$app/paths";
  import * as Alert from "$lib/components/ui/alert/index.js";
  import { Label } from "$lib/components/ui/label/index.js";
  import * as RadioGroup from "$lib/components/ui/radio-group/index.js";
  import { Switch } from "$lib/components/ui/switch/index.js";
  import { m } from "$lib/paraglide/messages";
  import { AlertCircle, Info, Sparkles } from "lucide-svelte";
  import PolicySection from "./PolicySection.svelte";

  type PromptOption = {
    id: string;
    name: string;
    description?: string | null;
  };

  type Props = {
    promptEnabled: boolean;
    selectedPromptId: string | null;
    promptOptions: PromptOption[];
    promptSummary: string;
    badgeVariant: (enabled: boolean, valid: boolean) => "default" | "outline" | "destructive";
  };

  let {
    promptEnabled = $bindable(),
    selectedPromptId = $bindable(),
    promptOptions,
    promptSummary,
    badgeVariant
  }: Props = $props();
</script>

<PolicySection
  id="prompt"
  title={m.governance_prompt_heading()}
  description={m.governance_prompt_section_desc()}
  summary={promptSummary}
  summaryVariant={badgeVariant(promptEnabled, selectedPromptId !== null)}
>
  {#snippet icon()}
    <Sparkles class="h-5 w-5" />
  {/snippet}

  <div class="flex items-center justify-between gap-3">
    <Label for="prompt-enabled" class="text-sm font-medium">
      {m.governance_prompt_toggle_label()}
    </Label>
    <Switch id="prompt-enabled" bind:checked={promptEnabled} aria-describedby="prompt-help" />
  </div>

  {#if promptEnabled}
    {#if promptOptions.length === 0}
      <Alert.Root class="border-caution/35 bg-caution/8 dark:bg-caution/12">
        <Info class="text-caution" />
        <Alert.Description class="text-secondary">
          {m.governance_prompt_library_empty()}
          <a
            class="text-accent-default mt-1 inline-block underline"
            href={resolve("/admin/prompt-library")}
          >
            {m.governance_prompt_create_in_library()}
          </a>
        </Alert.Description>
      </Alert.Root>
    {:else}
      <p id="prompt-help" class="text-secondary text-sm">
        {m.governance_prompt_help_enabled()}
      </p>
      <RadioGroup.Root bind:value={() => selectedPromptId ?? "", (v) => (selectedPromptId = v)}>
        <div class="space-y-2">
          {#each promptOptions as p (p.id)}
            <Label
              for={`p-${p.id}`}
              class="border-default hover:border-stronger aria-checked:border-accent-default flex cursor-pointer items-start gap-3 rounded-lg border p-3 transition-colors"
            >
              <RadioGroup.Item value={p.id} id={`p-${p.id}`} class="mt-0.5" />
              <div class="flex-1">
                <div class="text-sm font-medium">{p.name}</div>
                {#if p.description}
                  <div class="text-secondary mt-0.5 text-xs">{p.description}</div>
                {/if}
              </div>
            </Label>
          {/each}
        </div>
      </RadioGroup.Root>
      {#if !selectedPromptId}
        <p class="text-destructive flex items-center gap-2 text-sm" role="alert">
          <AlertCircle class="h-4 w-4 shrink-0" aria-hidden="true" />
          {m.governance_prompt_error_required()}
        </p>
      {/if}
    {/if}
  {:else}
    <p id="prompt-help" class="text-secondary text-sm">
      {m.governance_prompt_help_disabled()}
    </p>
  {/if}
</PolicySection>
