// frontend/apps/web/src/lib/features/skills/SkillForm.svelte
<script lang="ts">
  import { useId } from "bits-ui";
  import { ChevronDown, ChevronRight, CircleAlert } from "lucide-svelte";
  import * as Alert from "$lib/components/ui/alert/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import * as Field from "$lib/components/ui/field/index.js";
  import { Input } from "$lib/components/ui/input/index.js";
  import { Textarea } from "$lib/components/ui/textarea/index.js";
  import { getErrorMessage } from "$lib/core/errors";
  import { m } from "$lib/paraglide/messages";
  import { tick, untrack } from "svelte";
  import type { SkillFormValue, SkillRevisionFormValue } from "./skillBindings";

  type SharedProps = {
    class?: string;
    submitLabel?: string;
    submittingLabel?: string;
    showDiscardAction?: boolean;
    onDirtyChange?: (dirty: boolean) => void;
  };

  type CreateProps = SharedProps & {
    mode?: "create";
    initialValue?: Partial<SkillFormValue>;
    onSubmit: (value: SkillFormValue) => Promise<void>;
  };

  type RevisionProps = SharedProps & {
    mode: "revision";
    initialValue?: Partial<SkillRevisionFormValue>;
    onSubmit: (value: SkillRevisionFormValue) => Promise<void>;
  };

  type Props = CreateProps | RevisionProps;

  let props: Props = $props();

  const id = useId();
  const displayNameId = `${id}-display-name`;
  const descriptionId = `${id}-description`;
  const instructionsId = `${id}-instructions`;
  const advancedId = `${id}-advanced`;
  const slugId = `${id}-slug`;

  const initialDisplayName = untrack(() => props.initialValue?.display_name ?? "");
  const initialDescription = untrack(() => props.initialValue?.description ?? "");
  const initialInstructions = untrack(() => props.initialValue?.instructions ?? "");
  const initialSlug = untrack(() =>
    props.mode === "revision"
      ? ""
      : (props.initialValue?.slug ?? deriveSkillSlug(initialDisplayName))
  );
  const initialSlugCustomized = untrack(
    () => props.mode !== "revision" && props.initialValue?.slug !== undefined
  );

  let displayName = $state(initialDisplayName);
  let description = $state(initialDescription);
  let instructions = $state(initialInstructions);
  let slug = $state(initialSlug);
  let slugCustomized = $state(initialSlugCustomized);
  let baseline = $state({
    displayName: initialDisplayName,
    description: initialDescription,
    instructions: initialInstructions,
    slug: initialSlug,
    slugCustomized: initialSlugCustomized
  });
  let advancedOpen = $state(false);
  let submitAttempted = $state(false);
  let isSubmitting = $state(false);
  let hasSubmitted = $state(false);
  let formError = $state<string | null>(null);
  let displayNameInput = $state<HTMLInputElement | null>(null);
  let descriptionInput = $state<HTMLTextAreaElement | null>(null);
  let instructionsInput = $state<HTMLTextAreaElement | null>(null);
  let slugInput = $state<HTMLInputElement | null>(null);

  const isCreateMode = $derived(props.mode !== "revision");
  const resolvedSubmitLabel = $derived(
    props.submitLabel ?? (isCreateMode ? m.skills_create_action() : m.save_changes())
  );
  const resolvedSubmittingLabel = $derived(
    props.submittingLabel ?? (isCreateMode ? m.skills_creating() : m.saving())
  );
  const displayNameInvalid = $derived(submitAttempted && displayName.trim().length === 0);
  const descriptionInvalid = $derived(submitAttempted && description.trim().length === 0);
  const instructionsInvalid = $derived(submitAttempted && instructions.trim().length === 0);
  const slugInvalid = $derived(isCreateMode && submitAttempted && slug.trim().length === 0);
  const hasInvalidField = $derived(
    displayNameInvalid || descriptionInvalid || instructionsInvalid || slugInvalid
  );
  const dirty = $derived(
    displayName !== baseline.displayName ||
      description !== baseline.description ||
      instructions !== baseline.instructions ||
      (isCreateMode && slug !== baseline.slug)
  );

  $effect(() => {
    props.onDirtyChange?.(dirty);
  });

  function handleDisplayNameInput(event: Event) {
    if (slugCustomized) return;
    slug = deriveSkillSlug((event.currentTarget as HTMLInputElement).value);
  }

  function handleSlugInput() {
    slugCustomized = true;
  }

  function discardChanges() {
    displayName = baseline.displayName;
    description = baseline.description;
    instructions = baseline.instructions;
    slug = baseline.slug;
    slugCustomized = baseline.slugCustomized;
    submitAttempted = false;
    formError = null;
  }

  async function revealInvalidSlug() {
    advancedOpen = true;
    await tick();
    slugInput?.focus();
  }

  async function focusFirstInvalidField() {
    if (displayNameInvalid || descriptionInvalid || instructionsInvalid) {
      await tick();
      if (displayNameInvalid) displayNameInput?.focus();
      else if (descriptionInvalid) descriptionInput?.focus();
      else instructionsInput?.focus();
      return;
    }
    if (slugInvalid) await revealInvalidSlug();
  }

  async function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    submitAttempted = true;
    formError = null;
    if (hasInvalidField) {
      await focusFirstInvalidField();
      return;
    }

    isSubmitting = true;
    try {
      const content: SkillRevisionFormValue = {
        display_name: displayName.trim(),
        description: description.trim(),
        instructions: instructions.trim()
      };
      const submittedSlug = slug.trim();
      if (props.mode === "revision") {
        await props.onSubmit(content);
      } else {
        await props.onSubmit({ ...content, slug: submittedSlug });
      }
      displayName = content.display_name;
      description = content.description;
      instructions = content.instructions;
      slug = submittedSlug;
      baseline = {
        displayName: content.display_name,
        description: content.description,
        instructions: content.instructions,
        slug: submittedSlug,
        slugCustomized
      };
      hasSubmitted = true;
      submitAttempted = false;
    } catch (error) {
      formError = getErrorMessage(error);
    } finally {
      isSubmitting = false;
    }
  }

  function deriveSkillSlug(value: string): string {
    return value
      .normalize("NFKD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 64)
      .replace(/-+$/g, "");
  }
</script>

<form
  class={["flex w-full max-w-[80ch] flex-col gap-5", props.class]}
  onsubmit={handleSubmit}
  aria-busy={isSubmitting}
  novalidate
>
  <Field.Group>
    <Field.Field data-invalid={displayNameInvalid || undefined}>
      <Field.Label for={displayNameId}>{m.skills_display_name_label()}</Field.Label>
      <Input
        bind:ref={displayNameInput}
        id={displayNameId}
        bind:value={displayName}
        oninput={handleDisplayNameInput}
        aria-invalid={displayNameInvalid || undefined}
        aria-describedby={`${displayNameId}-description`}
        disabled={isSubmitting}
        maxlength={200}
        required
      />
      <Field.Description class="max-w-[65ch]" id={`${displayNameId}-description`}>
        {m.skills_display_name_description()}
      </Field.Description>
      {#if displayNameInvalid}
        <Field.Error>{m.skills_required_field()}</Field.Error>
      {/if}
    </Field.Field>

    <Field.Field data-invalid={descriptionInvalid || undefined}>
      <Field.Label for={descriptionId}>{m.skills_description_label()}</Field.Label>
      <Textarea
        bind:ref={descriptionInput}
        id={descriptionId}
        bind:value={description}
        aria-invalid={descriptionInvalid || undefined}
        aria-describedby={`${descriptionId}-description`}
        disabled={isSubmitting}
        class="min-h-24"
        rows={3}
        maxlength={1024}
        required
      />
      <Field.Description class="max-w-[65ch]" id={`${descriptionId}-description`}>
        {m.skills_description_description()}
      </Field.Description>
      {#if descriptionInvalid}
        <Field.Error>{m.skills_required_field()}</Field.Error>
      {/if}
    </Field.Field>

    <Field.Field data-invalid={instructionsInvalid || undefined}>
      <Field.Label for={instructionsId}>{m.skills_instructions_label()}</Field.Label>
      <Textarea
        bind:ref={instructionsInput}
        id={instructionsId}
        bind:value={instructions}
        aria-invalid={instructionsInvalid || undefined}
        aria-describedby={`${instructionsId}-description`}
        disabled={isSubmitting}
        class={["max-h-[min(50dvh,32rem)] overflow-y-auto", isCreateMode ? "min-h-48" : "min-h-72"]}
        rows={isCreateMode ? 8 : 12}
        required
      />
      <Field.Description class="max-w-[65ch]" id={`${instructionsId}-description`}>
        {m.skills_instructions_description()}
      </Field.Description>
      {#if instructionsInvalid}
        <Field.Error>{m.skills_required_field()}</Field.Error>
      {/if}
    </Field.Field>
  </Field.Group>

  {#if isCreateMode}
    <div>
      <Button
        type="button"
        variant="ghost"
        size="sm"
        aria-expanded={advancedOpen}
        aria-controls={advancedId}
        onclick={() => (advancedOpen = !advancedOpen)}
      >
        {#if advancedOpen}
          <ChevronDown data-icon="inline-start" aria-hidden="true" />
        {:else}
          <ChevronRight data-icon="inline-start" aria-hidden="true" />
        {/if}
        {m.skills_advanced_options()}
      </Button>
    </div>

    {#if advancedOpen}
      <div id={advancedId} class="border-border border-t pt-5">
        <Field.Field data-invalid={slugInvalid || undefined}>
          <Field.Label for={slugId}>{m.skills_slug_label()}</Field.Label>
          <Input
            bind:ref={slugInput}
            id={slugId}
            bind:value={slug}
            oninput={handleSlugInput}
            aria-invalid={slugInvalid || undefined}
            aria-describedby={`${slugId}-description`}
            disabled={isSubmitting}
            autocomplete="off"
            maxlength={64}
            required
          />
          <Field.Description class="max-w-[65ch]" id={`${slugId}-description`}>
            {m.skills_slug_description()}
          </Field.Description>
          {#if slugInvalid}
            <Field.Error>{m.skills_required_field()}</Field.Error>
          {/if}
        </Field.Field>
      </div>
    {/if}
  {/if}

  {#if formError}
    <Alert.Root variant="destructive">
      <CircleAlert aria-hidden="true" />
      <Alert.Title>
        {isCreateMode ? m.skills_form_error_title() : m.skills_revision_form_error_title()}
      </Alert.Title>
      <Alert.Description>{formError}</Alert.Description>
    </Alert.Root>
  {/if}

  <div
    class="border-border bg-background sticky bottom-0 z-10 -mx-1 flex min-h-14 flex-wrap items-center justify-between gap-3 border-t px-1 pt-3 pb-1"
  >
    <p class="text-muted-foreground text-sm" role="status" aria-live="polite">
      {dirty ? m.skills_form_unsaved_status() : hasSubmitted ? m.skills_form_saved_status() : ""}
    </p>
    <div class="ml-auto flex flex-wrap justify-end gap-2">
      {#if props.showDiscardAction && dirty}
        <Button type="button" variant="outline" disabled={isSubmitting} onclick={discardChanges}>
          {m.discard_all_changes()}
        </Button>
      {/if}
      <Button type="submit" disabled={isSubmitting} aria-busy={isSubmitting}>
        {isSubmitting ? resolvedSubmittingLabel : resolvedSubmitLabel}
      </Button>
    </div>
  </div>
</form>

// frontend/apps/web-next/src/features/skills/skill-form.tsx
"use client";

import { useTranslations } from "next-intl";
import { useEffect, useId, useRef, useState, type FormEvent } from "react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { getErrorMessage } from "@/lib/api/errors";
import {
  deriveSkillSlug,
  normalizedSkillContent,
  type SkillContent,
  type SkillCreation
} from "./skill-model";

type Props =
  | {
      mode: "create";
      onSubmit: (value: SkillCreation) => Promise<void>;
      initialValue?: never;
      onDirtyChange?: (dirty: boolean) => void;
    }
  | {
      mode: "revision";
      onSubmit: (value: SkillContent) => Promise<void>;
      initialValue: SkillContent;
      onDirtyChange?: (dirty: boolean) => void;
    };

export function SkillForm(props: Props) {
  const t = useTranslations();
  const onDirtyChange = props.onDirtyChange;
  const id = useId();
  const initial = props.mode === "revision" ? props.initialValue : null;
  const [name, setName] = useState(initial?.display_name ?? "");
  const [description, setDescription] = useState(initial?.description ?? "");
  const [instructions, setInstructions] = useState(initial?.instructions ?? "");
  const [slug, setSlug] = useState(deriveSkillSlug(initial?.display_name ?? ""));
  const [slugCustomized, setSlugCustomized] = useState(false);
  const [baseline, setBaseline] = useState({
    name: initial?.display_name ?? "",
    description: initial?.description ?? "",
    instructions: initial?.instructions ?? "",
    slug: deriveSkillSlug(initial?.display_name ?? "")
  });
  const [attempted, setAttempted] = useState(false);
  const [busy, setBusy] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const nameRef = useRef<HTMLInputElement>(null);
  const descriptionRef = useRef<HTMLTextAreaElement>(null);
  const instructionsRef = useRef<HTMLTextAreaElement>(null);
  const slugRef = useRef<HTMLInputElement>(null);
  const dirty =
    name !== baseline.name ||
    description !== baseline.description ||
    instructions !== baseline.instructions ||
    (props.mode === "create" && slug !== baseline.slug);

  useEffect(() => {
    if (!dirty) return;
    const warn = (event: BeforeUnloadEvent) => {
      event.preventDefault();
      event.returnValue = "";
    };
    window.addEventListener("beforeunload", warn);
    return () => window.removeEventListener("beforeunload", warn);
  }, [dirty]);

  useEffect(() => onDirtyChange?.(dirty), [dirty, onDirtyChange]);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (busy) return;
    setAttempted(true);
    setError(null);
    const content = normalizedSkillContent({
      display_name: name,
      description,
      instructions
    });
    const submittedSlug = slug.trim();
    if (!content.display_name) nameRef.current?.focus();
    else if (!content.description) descriptionRef.current?.focus();
    else if (!content.instructions) instructionsRef.current?.focus();
    else if (props.mode === "create" && !submittedSlug) {
      document.getElementById(`${id}-advanced`)?.setAttribute("open", "");
      slugRef.current?.focus();
    } else {
      setBusy(true);
      try {
        if (props.mode === "create") await props.onSubmit({ ...content, slug: submittedSlug });
        else await props.onSubmit(content);
        setName(content.display_name);
        setDescription(content.description);
        setInstructions(content.instructions);
        setSlug(submittedSlug);
        setBaseline({
          name: content.display_name,
          description: content.description,
          instructions: content.instructions,
          slug: submittedSlug
        });
        setAttempted(false);
        setSaved(true);
      } catch (cause) {
        setError(getErrorMessage(cause, t));
      } finally {
        setBusy(false);
      }
    }
  }

  function discard() {
    setName(baseline.name);
    setDescription(baseline.description);
    setInstructions(baseline.instructions);
    setSlug(baseline.slug);
    setAttempted(false);
    setError(null);
  }

  return (
    <form
      className="flex max-w-2xl flex-col gap-6"
      onSubmit={(event) => void submit(event)}
      noValidate
      aria-busy={busy}
    >
      <div className="space-y-2">
        <Label htmlFor={`${id}-name`}>{t("skills_display_name_label")}</Label>
        <Input
          ref={nameRef}
          id={`${id}-name`}
          value={name}
          maxLength={200}
          required
          disabled={busy}
          aria-invalid={attempted && !name.trim()}
          onChange={(event) => {
            setName(event.target.value);
            if (props.mode === "create" && !slugCustomized)
              setSlug(deriveSkillSlug(event.target.value));
          }}
        />
        <p className="text-muted-foreground text-xs">{t("skills_display_name_description")}</p>
        {attempted && !name.trim() && (
          <p className="text-destructive text-xs">{t("skills_required_field")}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor={`${id}-description`}>{t("skills_description_label")}</Label>
        <Textarea
          ref={descriptionRef}
          id={`${id}-description`}
          value={description}
          rows={3}
          maxLength={1024}
          required
          disabled={busy}
          aria-invalid={attempted && !description.trim()}
          onChange={(event) => setDescription(event.target.value)}
        />
        <p className="text-muted-foreground text-xs">{t("skills_description_description")}</p>
        {attempted && !description.trim() && (
          <p className="text-destructive text-xs">{t("skills_required_field")}</p>
        )}
      </div>
      <div className="space-y-2">
        <Label htmlFor={`${id}-instructions`}>{t("skills_instructions_label")}</Label>
        <Textarea
          ref={instructionsRef}
          id={`${id}-instructions`}
          value={instructions}
          rows={props.mode === "create" ? 8 : 12}
          className="max-h-[50dvh] min-h-48 overflow-y-auto font-mono text-sm"
          required
          disabled={busy}
          aria-invalid={attempted && !instructions.trim()}
          onChange={(event) => setInstructions(event.target.value)}
        />
        <p className="text-muted-foreground text-xs">{t("skills_instructions_description")}</p>
        {attempted && !instructions.trim() && (
          <p className="text-destructive text-xs">{t("skills_required_field")}</p>
        )}
      </div>
      {props.mode === "create" && (
        <details id={`${id}-advanced`} className="rounded-lg border p-4">
          <summary className="cursor-pointer text-sm font-medium">
            {t("skills_advanced_options")}
          </summary>
          <div className="mt-4 space-y-2">
            <Label htmlFor={`${id}-slug`}>{t("skills_slug_label")}</Label>
            <Input
              ref={slugRef}
              id={`${id}-slug`}
              value={slug}
              maxLength={64}
              autoComplete="off"
              required
              disabled={busy}
              aria-invalid={attempted && !slug.trim()}
              onChange={(event) => {
                setSlug(event.target.value);
                setSlugCustomized(true);
              }}
            />
            <p className="text-muted-foreground text-xs">{t("skills_slug_description")}</p>
            {attempted && !slug.trim() && (
              <p className="text-destructive text-xs">{t("skills_required_field")}</p>
            )}
          </div>
        </details>
      )}
      {error && (
        <Alert variant="destructive" role="alert">
          <AlertTitle>
            {t(
              props.mode === "create"
                ? "skills_form_error_title"
                : "skills_revision_form_error_title"
            )}
          </AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}
      <div className="bg-background sticky bottom-0 flex flex-wrap items-center justify-between gap-3 border-t py-3">
        <p className="text-muted-foreground text-sm" role="status">
          {dirty ? t("skills_form_unsaved_status") : saved ? t("skills_form_saved_status") : ""}
        </p>
        <div className="flex gap-2">
          {dirty && (
            <Button type="button" variant="outline" disabled={busy} onClick={discard}>
              {t("discard_all_changes")}
            </Button>
          )}
          <Button type="submit" disabled={busy}>
            {busy
              ? t(props.mode === "create" ? "skills_creating" : "saving")
              : t(props.mode === "create" ? "skills_create_action" : "save_changes")}
          </Button>
        </div>
      </div>
    </form>
  );
}
