// frontend/apps/web/src/lib/features/skills/SkillRevisionHistory.svelte
<script lang="ts">
  import type {
    SkillRevisionPublic,
    SkillRevisionRestorePublic,
    SkillRevisionSummaryPage,
    SkillRevisionSummaryPublic
  } from "@eneo/eneo-js";
  import { Eye, LoaderCircle, RotateCcw } from "lucide-svelte";
  import * as Alert from "$lib/components/ui/alert/index.js";
  import * as AlertDialog from "$lib/components/ui/alert-dialog/index.js";
  import { Badge } from "$lib/components/ui/badge/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import * as Card from "$lib/components/ui/card/index.js";
  import * as Dialog from "$lib/components/ui/dialog/index.js";
  import * as Table from "$lib/components/ui/table/index.js";
  import { getErrorMessage } from "$lib/core/errors";
  import { m } from "$lib/paraglide/messages";
  import { getLocale } from "$lib/paraglide/runtime";
  import { tick, untrack } from "svelte";

  type Props = {
    currentRevision: SkillRevisionPublic;
    initialPage: SkillRevisionSummaryPage;
    canRestore: boolean;
    hasUnsavedChanges: boolean;
    onLoadMore: (cursor: string) => Promise<SkillRevisionSummaryPage>;
    onView: (revisionId: string) => Promise<SkillRevisionPublic>;
    onRestore: (
      revisionId: string,
      reviewedCurrentRevisionId: string
    ) => Promise<SkillRevisionRestorePublic>;
    onLoadCurrent: () => Promise<SkillRevisionPublic>;
    onAnnounce?: (message: string) => Promise<void> | void;
    onRestored?: (outcome: SkillRevisionRestorePublic) => Promise<void>;
  };

  let {
    currentRevision,
    initialPage,
    canRestore,
    hasUnsavedChanges,
    onLoadMore,
    onView,
    onRestore,
    onLoadCurrent,
    onAnnounce,
    onRestored
  }: Props = $props();

  let revisions = $state(untrack(() => [...initialPage.items]));
  let comparisonCurrentRevision = $state(untrack(() => currentRevision));
  let nextCursor = $state(untrack(() => initialPage.next_cursor ?? null));
  let loadingMore = $state(false);
  let loadError = $state<string | null>(null);
  let viewingRevisionId = $state<string | null>(null);
  let previewError = $state<string | null>(null);
  let viewedRevision = $state<SkillRevisionPublic | null>(null);
  let restoreTarget = $state<SkillRevisionPublic | null>(null);
  let restoring = $state(false);
  let restoreError = $state<string | null>(null);

  function formatCreatedAt(value: string): string {
    return new Date(value).toLocaleString(getLocale() === "sv" ? "sv-SE" : "en-US", {
      dateStyle: "short",
      timeStyle: "short"
    });
  }

  function requestRestore(revision: SkillRevisionPublic) {
    viewedRevision = null;
    restoreError = null;
    restoreTarget = revision;
  }

  function setRestoreOpen(open: boolean) {
    if (open || restoring) return;
    restoreTarget = null;
    restoreError = null;
  }

  function isConflict(error: unknown): error is { status: number } {
    return typeof error === "object" && error !== null && "status" in error && error.status === 409;
  }

  function asSummary(revision: SkillRevisionPublic): SkillRevisionSummaryPublic {
    return {
      id: revision.id,
      skill_id: revision.skill_id,
      revision_number: revision.revision_number,
      display_name: revision.display_name,
      created_at: revision.created_at
    };
  }

  async function viewRevision(revision: SkillRevisionSummaryPublic) {
    if (viewingRevisionId !== null) return;
    previewError = null;
    if (revision.id === comparisonCurrentRevision.id) {
      viewedRevision = comparisonCurrentRevision;
      return;
    }
    viewingRevisionId = revision.id;
    try {
      viewedRevision = await onView(revision.id);
    } catch (error) {
      previewError = getErrorMessage(error) || m.skills_library_preview_error();
    } finally {
      viewingRevisionId = null;
    }
  }

  async function loadOlder() {
    if (nextCursor === null || loadingMore) return;
    const cursor = nextCursor;
    loadingMore = true;
    loadError = null;
    try {
      const page = await onLoadMore(cursor);
      revisions = [...revisions, ...page.items];
      nextCursor = page.next_cursor ?? null;
    } catch (error) {
      loadError = getErrorMessage(error) || m.skills_library_load_older_error();
    } finally {
      loadingMore = false;
    }
  }

  async function performRestore() {
    if (!restoreTarget || restoring) return;
    const source = restoreTarget;
    restoring = true;
    restoreError = null;
    let outcome: SkillRevisionRestorePublic;
    try {
      outcome = await onRestore(source.id, comparisonCurrentRevision.id);
    } catch (error) {
      restoreError = getErrorMessage(error) || m.skills_library_restore_error();
      if (isConflict(error)) {
        try {
          const latest = await onLoadCurrent();
          comparisonCurrentRevision = latest;
          revisions = [
            asSummary(latest),
            ...revisions.filter((revision) => revision.id !== latest.id)
          ];
          restoreTarget = null;
          viewedRevision = source;
        } catch (refreshError) {
          restoreError = getErrorMessage(refreshError) || m.skills_library_restore_refresh_error();
        }
      }
      restoring = false;
      return;
    }

    const message = outcome.created
      ? m.skills_library_restore_success({
          sourceRevision: String(outcome.restored_from_revision_number),
          newRevision: String(outcome.revision.revision_number)
        })
      : m.skills_library_restore_noop();
    await onAnnounce?.(message);
    restoreTarget = null;
    restoring = false;
    await tick();
    if (outcome.created || outcome.revision.id !== comparisonCurrentRevision.id) {
      try {
        await onRestored?.(outcome);
      } catch {
        loadError = m.skills_library_restore_refresh_error();
      }
    }
  }

  function revisionTitle(revision: SkillRevisionPublic | SkillRevisionSummaryPublic): string {
    return m.skills_revision_label({ revision: String(revision.revision_number) });
  }
</script>

{#snippet revisionPreview(revision: SkillRevisionPublic, isCurrent = false)}
  <Card.Root>
    <Card.Header class="gap-2">
      <div class="flex flex-wrap items-center gap-2">
        <Card.Title class="text-base">{revisionTitle(revision)}</Card.Title>
        {#if isCurrent}
          <Badge variant="secondary">{m.skills_library_current_revision()}</Badge>
        {/if}
      </div>
      <Card.Description>{formatCreatedAt(revision.created_at)}</Card.Description>
    </Card.Header>
    <Card.Content>
      <dl class="flex flex-col gap-4">
        <div class="flex flex-col gap-1">
          <dt class="text-muted-foreground text-xs font-medium">{m.name()}</dt>
          <dd class="text-sm">{revision.display_name}</dd>
        </div>
        <div class="flex flex-col gap-1">
          <dt class="text-muted-foreground text-xs font-medium">{m.description()}</dt>
          <dd class="text-sm">{revision.description}</dd>
        </div>
        <div class="flex flex-col gap-1">
          <dt class="text-muted-foreground text-xs font-medium">
            {m.skills_instructions_label()}
          </dt>
          <dd
            class="border-border bg-muted/25 max-h-72 overflow-y-auto rounded-md border p-3 text-sm break-words whitespace-pre-wrap"
          >
            {revision.instructions}
          </dd>
        </div>
      </dl>
    </Card.Content>
  </Card.Root>
{/snippet}

<Card.Root>
  <Table.Root>
    <Table.Header>
      <Table.Row>
        <Table.Head>{m.skills_library_revision_column()}</Table.Head>
        <Table.Head>{m.name()}</Table.Head>
        <Table.Head>{m.skills_library_created_column()}</Table.Head>
        <Table.Head class="w-16 text-right">{m.actions()}</Table.Head>
      </Table.Row>
    </Table.Header>
    <Table.Body>
      {#each revisions as revision (revision.id)}
        {@const isCurrent = revision.id === comparisonCurrentRevision.id}
        <Table.Row>
          <Table.Cell>
            <div class="flex flex-wrap items-center gap-2">
              <span class="font-medium">
                {m.skills_revision_label({ revision: String(revision.revision_number) })}
              </span>
              {#if isCurrent}
                <Badge variant="secondary">{m.skills_library_current_revision()}</Badge>
              {/if}
            </div>
          </Table.Cell>
          <Table.Cell>{revision.display_name}</Table.Cell>
          <Table.Cell class="text-muted-foreground text-sm">
            {formatCreatedAt(revision.created_at)}
          </Table.Cell>
          <Table.Cell class="text-right">
            <div class="flex items-center justify-end gap-1">
              <Button
                variant="ghost"
                size="icon-sm"
                disabled={viewingRevisionId !== null}
                title={m.view()}
                aria-label={m.skills_library_view_revision_aria({
                  revision: String(revision.revision_number)
                })}
                onclick={() => void viewRevision(revision)}
              >
                {#if viewingRevisionId === revision.id}
                  <LoaderCircle class="animate-spin" aria-hidden="true" />
                {:else}
                  <Eye aria-hidden="true" />
                {/if}
              </Button>
            </div>
          </Table.Cell>
        </Table.Row>
      {/each}
    </Table.Body>
  </Table.Root>
  {#if nextCursor !== null || loadError || previewError}
    <Card.Footer class="flex-col items-center gap-3 border-t">
      {#if loadError}
        <p class="text-destructive text-sm" role="alert">{loadError}</p>
      {/if}
      {#if previewError}
        <p class="text-destructive text-sm" role="alert">{previewError}</p>
      {/if}
      {#if nextCursor !== null}
        <Button variant="outline" disabled={loadingMore} onclick={loadOlder}>
          {#if loadingMore}
            <LoaderCircle class="animate-spin" aria-hidden="true" />
            {m.skills_library_loading_older()}
          {:else}
            {m.skills_library_load_older()}
          {/if}
        </Button>
      {/if}
    </Card.Footer>
  {/if}
</Card.Root>

<Dialog.Root
  open={viewedRevision !== null}
  onOpenChange={(open) => !open && (viewedRevision = null)}
>
  <Dialog.Content
    class="max-h-[calc(100dvh-2rem)] overflow-y-auto sm:max-w-2xl"
    closeLabel={m.close()}
  >
    <Dialog.Header>
      <Dialog.Title>
        {viewedRevision?.id === comparisonCurrentRevision.id
          ? m.skills_library_view_revision_title({
              revision: String(viewedRevision.revision_number)
            })
          : m.skills_library_compare_revision_title({
              revision: String(viewedRevision?.revision_number ?? "")
            })}
      </Dialog.Title>
      {#if viewedRevision?.id !== comparisonCurrentRevision.id}
        <Dialog.Description>{m.skills_library_compare_revision_description()}</Dialog.Description>
      {/if}
    </Dialog.Header>
    {#if restoreError}
      <Alert.Root variant="destructive">
        <Alert.Title>{m.skills_library_restore_error()}</Alert.Title>
        <Alert.Description>{restoreError}</Alert.Description>
      </Alert.Root>
      {#if hasUnsavedChanges}
        <Alert.Root>
          <Alert.Title>{m.skills_library_restore_unsaved_title()}</Alert.Title>
          <Alert.Description>{m.skills_library_restore_unsaved_warning()}</Alert.Description>
        </Alert.Root>
      {/if}
    {/if}
    {#if viewedRevision}
      {#if viewedRevision.id === comparisonCurrentRevision.id}
        {@render revisionPreview(viewedRevision, true)}
      {:else}
        <div class="grid gap-4 md:grid-cols-2">
          {@render revisionPreview(viewedRevision)}
          {@render revisionPreview(comparisonCurrentRevision, true)}
        </div>
      {/if}
    {/if}
    <Dialog.Footer>
      {#if canRestore && viewedRevision && viewedRevision.id !== comparisonCurrentRevision.id}
        <Button variant="outline" onclick={() => viewedRevision && requestRestore(viewedRevision)}>
          <RotateCcw aria-hidden="true" />
          {m.skills_library_restore_revision_from_preview()}
        </Button>
      {/if}
      <Button onclick={() => (viewedRevision = null)}>{m.close()}</Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>

<AlertDialog.Root open={restoreTarget !== null} onOpenChange={setRestoreOpen}>
  <AlertDialog.Content>
    <AlertDialog.Header>
      <AlertDialog.Title>
        {m.skills_library_restore_title({
          revision: String(restoreTarget?.revision_number ?? "")
        })}
      </AlertDialog.Title>
      <AlertDialog.Description>
        {m.skills_library_restore_description({
          revision: String(restoreTarget?.revision_number ?? "")
        })}
      </AlertDialog.Description>
    </AlertDialog.Header>
    {#if hasUnsavedChanges}
      <Alert.Root>
        <Alert.Title>{m.skills_library_restore_unsaved_title()}</Alert.Title>
        <Alert.Description>{m.skills_library_restore_unsaved_warning()}</Alert.Description>
      </Alert.Root>
    {/if}
    {#if restoreError}
      <Alert.Root variant="destructive">
        <Alert.Title>{m.skills_library_restore_error()}</Alert.Title>
        <Alert.Description>{restoreError}</Alert.Description>
      </Alert.Root>
    {/if}
    <AlertDialog.Footer>
      <AlertDialog.Cancel disabled={restoring}>{m.cancel()}</AlertDialog.Cancel>
      <AlertDialog.Action
        disabled={restoring}
        onclick={(event) => {
          event.preventDefault();
          void performRestore();
        }}
      >
        {#if restoring}
          <LoaderCircle class="animate-spin" aria-hidden="true" />
          {m.skills_library_restoring()}
        {:else}
          <RotateCcw aria-hidden="true" />
          {m.skills_library_restore_action()}
        {/if}
      </AlertDialog.Action>
    </AlertDialog.Footer>
  </AlertDialog.Content>
</AlertDialog.Root>

// frontend/apps/web-next/src/features/skills/skill-revision-history.tsx
"use client";

import { useInfiniteQuery, useQuery, useQueryClient } from "@tanstack/react-query";
import { Eye, RotateCcw } from "lucide-react";
import { useLocale, useTranslations } from "next-intl";
import { useState } from "react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle
} from "@/components/ui/alert-dialog";
import { browserApi } from "@/lib/api/browser";
import { EneoApiError, getErrorMessage, unwrap } from "@/lib/api/errors";
import type { Schema } from "@/lib/api/models";
import { ORGANIZATION_SKILLS_KEY } from "./organization-skills";

type Skill = Schema<"OrganizationSkillPublic">;
type Revision = Schema<"SkillRevisionPublic">;

function RevisionContent({ revision, current }: { revision: Revision; current: Revision }) {
  const t = useTranslations();
  return (
    <dl className="grid gap-4 sm:grid-cols-2">
      {(["display_name", "description", "instructions"] as const).map((field) => (
        <div key={field} className={field === "instructions" ? "sm:col-span-2" : ""}>
          <dt className="text-muted-foreground mb-1 flex gap-2 text-xs font-medium">
            {t(
              field === "display_name"
                ? "name"
                : field === "description"
                  ? "description"
                  : "skills_instructions_label"
            )}
            {revision[field] !== current[field] && (
              <Badge variant="outline">{t("skills_library_changed_field")}</Badge>
            )}
          </dt>
          <dd
            className={
              field === "instructions"
                ? "bg-muted/40 max-h-80 overflow-y-auto rounded-md border p-3 font-mono text-xs whitespace-pre-wrap"
                : "text-sm"
            }
          >
            {revision[field]}
          </dd>
        </div>
      ))}
    </dl>
  );
}

export function SkillRevisionHistory({ skill, unsaved }: { skill: Skill; unsaved: boolean }) {
  const t = useTranslations();
  const locale = useLocale();
  const queryClient = useQueryClient();
  const [viewId, setViewId] = useState<string | null>(null);
  const [restoreId, setRestoreId] = useState<string | null>(null);
  const [restoring, setRestoring] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [announcement, setAnnouncement] = useState("");
  const path = { skill_id: skill.id };
  const revisions = useInfiniteQuery({
    queryKey: [...ORGANIZATION_SKILLS_KEY, skill.id, "revisions"],
    initialPageParam: null as string | null,
    queryFn: ({ pageParam }) =>
      unwrap(
        browserApi.GET("/api/v1/skills/organization/{skill_id}/revisions/", {
          params: { path, query: { cursor: pageParam } }
        })
      ),
    getNextPageParam: (page) => page.next_cursor ?? undefined,
    retry: false
  });
  const preview = useQuery({
    queryKey: [...ORGANIZATION_SKILLS_KEY, skill.id, "revision", viewId],
    enabled: Boolean(viewId) && viewId !== skill.current_revision_id,
    queryFn: () =>
      unwrap(
        browserApi.GET("/api/v1/skills/organization/{skill_id}/revisions/{revision_id}/", {
          params: { path: { ...path, revision_id: viewId as string } }
        })
      ),
    retry: false
  });
  const revision = viewId === skill.current_revision_id ? skill.current_revision : preview.data;
  const items = revisions.data?.pages.flatMap((page) => page.items) ?? [];

  async function restore() {
    if (!restoreId || restoring || skill.removed_at) return;
    setRestoring(true);
    setError(null);
    try {
      const outcome = await unwrap(
        browserApi.POST(
          "/api/v1/skills/organization/{skill_id}/revisions/{source_revision_id}/restore/",
          {
            params: { path: { ...path, source_revision_id: restoreId } },
            body: { reviewed_current_revision_id: skill.current_revision_id }
          }
        )
      );
      setRestoreId(null);
      setViewId(null);
      setAnnouncement(
        outcome.created
          ? t("skills_library_restore_success", {
              sourceRevision: String(outcome.restored_from_revision_number),
              newRevision: String(outcome.revision.revision_number)
            })
          : t("skills_library_restore_noop")
      );
      if (outcome.created)
        await queryClient.invalidateQueries({ queryKey: ORGANIZATION_SKILLS_KEY });
    } catch (cause) {
      setError(getErrorMessage(cause, t));
      if (cause instanceof EneoApiError && cause.status === 409) {
        await queryClient.invalidateQueries({ queryKey: [...ORGANIZATION_SKILLS_KEY, skill.id] });
        setRestoreId(null);
      }
    } finally {
      setRestoring(false);
    }
  }

  return (
    <section className="space-y-4" aria-labelledby="organization-skill-history-heading">
      <div>
        <h2 id="organization-skill-history-heading" className="text-lg font-semibold">
          {t("skills_library_history_heading")}
        </h2>
        <p className="text-muted-foreground text-sm">{t("skills_library_history_description")}</p>
      </div>
      <p role="status" className={announcement ? "text-sm" : "sr-only"}>
        {announcement}
      </p>
      {revisions.isPending ? (
        <p role="status">{t("loading")}</p>
      ) : revisions.isError && !revisions.data ? (
        <Alert variant="destructive" role="alert">
          <AlertTitle>{t("request_failed")}</AlertTitle>
          <AlertDescription>
            <Button variant="outline" onClick={() => void revisions.refetch()}>
              {t("retry")}
            </Button>
          </AlertDescription>
        </Alert>
      ) : (
        <>
          <div className="divide-y rounded-lg border">
            {items.map((item) => (
              <div key={item.id} className="flex flex-wrap items-center gap-3 p-3">
                <div className="min-w-0 flex-1">
                  <p className="flex flex-wrap items-center gap-2 text-sm font-medium">
                    {t("skills_revision_label", { revision: String(item.revision_number) })}
                    {item.id === skill.current_revision_id && (
                      <Badge variant="secondary">{t("skills_library_current_revision")}</Badge>
                    )}
                  </p>
                  <p className="text-muted-foreground truncate text-xs">
                    {item.display_name} ·{" "}
                    {new Date(item.created_at).toLocaleString(locale, {
                      dateStyle: "short",
                      timeStyle: "short"
                    })}
                  </p>
                </div>
                <Button
                  variant="outline"
                  size="sm"
                  aria-label={t("skills_library_view_revision_aria", {
                    revision: String(item.revision_number)
                  })}
                  onClick={() => {
                    setError(null);
                    setViewId(item.id);
                  }}
                >
                  <Eye className="size-4" />
                  {t("preview")}
                </Button>
              </div>
            ))}
          </div>
          {revisions.hasNextPage && (
            <Button
              variant="outline"
              disabled={revisions.isFetchingNextPage}
              onClick={() => void revisions.fetchNextPage()}
            >
              {revisions.isFetchingNextPage
                ? t("skills_library_loading_older")
                : t("skills_library_load_older")}
            </Button>
          )}
          {revisions.isFetchNextPageError && (
            <Alert variant="destructive" role="alert">
              <AlertTitle>{t("skills_library_load_older_error")}</AlertTitle>
              <AlertDescription>
                <Button variant="outline" onClick={() => void revisions.fetchNextPage()}>
                  {t("retry")}
                </Button>
              </AlertDescription>
            </Alert>
          )}
        </>
      )}
      <Dialog
        open={viewId !== null}
        onOpenChange={(open) => {
          if (!open && !restoreId) setViewId(null);
        }}
      >
        <DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-3xl">
          <DialogHeader>
            <DialogTitle>
              {t("skills_library_view_revision_title", {
                revision: String(revision?.revision_number ?? "")
              })}
            </DialogTitle>
          </DialogHeader>
          {preview.isPending && viewId !== skill.current_revision_id ? (
            <p role="status">{t("loading")}</p>
          ) : preview.isError ? (
            <Alert variant="destructive" role="alert">
              <AlertTitle>{t("skills_library_preview_error")}</AlertTitle>
              <AlertDescription>
                <Button variant="outline" onClick={() => void preview.refetch()}>
                  {t("retry")}
                </Button>
              </AlertDescription>
            </Alert>
          ) : revision ? (
            <>
              <RevisionContent revision={revision} current={skill.current_revision} />
              {!skill.removed_at && revision.id !== skill.current_revision_id && (
                <Button
                  className="w-fit"
                  disabled={unsaved}
                  onClick={() => {
                    setRestoreId(revision.id);
                    setViewId(null);
                  }}
                >
                  <RotateCcw className="size-4" />
                  {t("skills_library_restore_revision_from_preview")}
                </Button>
              )}
            </>
          ) : null}
        </DialogContent>
      </Dialog>
      <AlertDialog
        open={restoreId !== null}
        onOpenChange={(open) => {
          if (!open && !restoring) setRestoreId(null);
        }}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              {t("skills_library_restore_title", {
                revision: String(items.find((item) => item.id === restoreId)?.revision_number ?? "")
              })}
            </AlertDialogTitle>
            <AlertDialogDescription>
              {t("skills_library_restore_description", {
                revision: String(items.find((item) => item.id === restoreId)?.revision_number ?? "")
              })}
            </AlertDialogDescription>
          </AlertDialogHeader>
          {error && (
            <Alert variant="destructive" role="alert">
              <AlertTitle>{t("skills_library_restore_error")}</AlertTitle>
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
          <AlertDialogFooter>
            <AlertDialogCancel disabled={restoring}>{t("cancel")}</AlertDialogCancel>
            <Button disabled={restoring || unsaved} onClick={() => void restore()}>
              {restoring ? t("skills_library_restoring") : t("skills_library_restore_action")}
            </Button>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </section>
  );
}
