// frontend/apps/web/src/routes/(app)/admin/personal-assistant/configuration/FilePolicySection.svelte
<!--
    Copyright (c) 2026 Sundsvalls Kommun

    Licensed under the MIT License.
-->

<script lang="ts">
  import { Label } from "$lib/components/ui/label/index.js";
  import { Switch } from "$lib/components/ui/switch/index.js";
  import { m } from "$lib/paraglide/messages";
  import { Paperclip } from "lucide-svelte";
  import PolicySection from "$lib/features/admin/PolicySection.svelte";
  import OpenFilesHelp from "$lib/features/assistants/components/OpenFilesHelp.svelte";

  type Props = {
    /** "On" lets assistants read large attachments with a tool instead of
        inlining their whole text (backend: inline_file_text = false). The
        originals are served from whichever store holds them (PostgreSQL or
        object storage), so the switch needs no storage prerequisite. */
    openFilesEnabled: boolean;
    summary: string;
  };

  let { openFilesEnabled = $bindable(), summary }: Props = $props();
</script>

<PolicySection
  id="files"
  title={m.governance_files_heading()}
  description={m.governance_files_section_desc()}
  {summary}
  summaryVariant="outline"
>
  {#snippet icon()}
    <Paperclip class="h-5 w-5" />
  {/snippet}

  <div class="flex items-start justify-between gap-4">
    <div>
      <Label for="files-large">{m.attachments_open_files_label()}</Label>
      <OpenFilesHelp id="files-large-help" />
    </div>
    <Switch id="files-large" bind:checked={openFilesEnabled} aria-describedby="files-large-help" />
  </div>
</PolicySection>

// frontend/apps/web-next/src/features/admin/governance/file-policy-section.tsx
"use client";

import { Paperclip } from "lucide-react";
import { useTranslations } from "next-intl";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { PolicySection } from "./policy-section";
import type { PolicyDraft } from "./use-policy-draft";

export function FilePolicySection({ draft }: { draft: PolicyDraft }) {
  const t = useTranslations();
  return (
    <PolicySection
      id="files"
      title={t("governance_files_heading")}
      description={t("governance_files_section_desc")}
      summary={draft.filesSummary}
      summaryVariant="outline"
      icon={<Paperclip className="size-5" />}
    >
      <div className="flex items-start justify-between gap-4">
        <div>
          <Label htmlFor="files-large">{t("attachments_open_files_label")}</Label>
          <p id="files-large-help" className="text-muted-foreground mt-1 text-sm">
            {t("attachments_open_files_help")}
          </p>
        </div>
        <Switch
          id="files-large"
          checked={draft.openFilesEnabled}
          onCheckedChange={draft.setOpenFiles}
          aria-describedby="files-large-help"
        />
      </div>
    </PolicySection>
  );
}
