// frontend/apps/web/src/routes/(app)/admin/personal-assistant/configuration/ModelRestrictionSection.svelte
<!--
    Copyright (c) 2026 Sundsvalls Kommun

    Licensed under the MIT License.
-->

<script lang="ts">
  import { Label } from "$lib/components/ui/label/index.js";
  import * as RadioGroup from "$lib/components/ui/radio-group/index.js";
  import { Switch } from "$lib/components/ui/switch/index.js";
  import { m } from "$lib/paraglide/messages";
  import { IconCPU } from "@intric/icons/CPU";
  import { AlertCircle } from "lucide-svelte";
  import PolicySection from "./PolicySection.svelte";

  type ModelSelection = { selected: boolean; isDefault: boolean };
  type CompletionModel = {
    id: string;
    provider_id?: string | null;
    nickname?: string | null;
    name: string;
  };
  type ReadableMap<K, V> = {
    entries(): IterableIterator<[K, V]>;
    get(key: K): V | undefined;
  };
  type ReadableSet<T> = {
    has(value: T): boolean;
    size: number;
  };

  type Props = {
    modelsEnabled: boolean;
    modelsByProvider: ReadableMap<string | null, CompletionModel[]>;
    modelSelections: ReadableMap<string, ModelSelection>;
    providerSelections: ReadableSet<string>;
    effectiveModelIds: ReadableSet<string>;
    defaultModelId: string | null;
    modelsSummary: string;
    defaultValid: boolean;
    badgeVariant: (enabled: boolean, valid: boolean) => "default" | "outline" | "destructive";
    providerName: (providerId: string | null) => string;
    setSingleDefault: (modelId: string) => void;
    toggleModelSelected: (modelId: string, selected: boolean) => void;
    toggleProvider: (providerId: string, selected: boolean) => void;
  };

  let {
    modelsEnabled = $bindable(),
    modelsByProvider,
    modelSelections,
    providerSelections,
    effectiveModelIds,
    defaultModelId,
    modelsSummary,
    defaultValid,
    badgeVariant,
    providerName,
    setSingleDefault,
    toggleModelSelected,
    toggleProvider
  }: Props = $props();
</script>

<PolicySection
  id="models"
  title={m.governance_models_heading()}
  description={m.governance_models_section_desc()}
  summary={modelsSummary}
  summaryVariant={badgeVariant(modelsEnabled, effectiveModelIds.size > 0 && defaultValid)}
>
  {#snippet icon()}
    <IconCPU class="h-5 w-5" />
  {/snippet}

  <div class="flex items-center justify-between gap-3">
    <Label for="models-enabled" class="text-sm font-medium">
      {m.governance_models_toggle_label()}
    </Label>
    <Switch id="models-enabled" bind:checked={modelsEnabled} aria-describedby="models-help" />
  </div>

  {#if modelsEnabled}
    <p id="models-help" class="text-secondary text-sm">
      {m.governance_models_help_enabled()}
    </p>
    <!-- One default model across all providers, so a single radio group wraps every table. -->
    <RadioGroup.Root
      bind:value={() => defaultModelId ?? "", (v) => v && setSingleDefault(v)}
      class="gap-3"
    >
      {#each Array.from(modelsByProvider.entries()) as [pid, providerModels] (pid ?? "_unprovided")}
        {@const isProviderSelected = pid !== null && providerSelections.has(pid)}
        <fieldset class="border-default overflow-hidden rounded-lg border">
          <legend class="sr-only">{providerName(pid)}</legend>
          <div
            class="bg-secondary border-default flex items-center justify-between gap-3 border-b px-4 py-3"
          >
            <div class="flex items-center gap-3">
              {#if pid !== null}
                <Switch
                  checked={isProviderSelected}
                  onCheckedChange={(v) => toggleProvider(pid, v)}
                  aria-label={m.governance_provider_allow_all_aria({
                    provider: providerName(pid)
                  })}
                />
              {:else}
                <div class="w-8" aria-hidden="true"></div>
              {/if}
              <div>
                <div class="text-primary text-sm font-semibold">
                  {providerName(pid)}
                </div>
                <div class="text-secondary text-xs">
                  {#if isProviderSelected}
                    {m.governance_provider_all_allowed()}
                  {:else if pid === null}
                    {m.governance_provider_no_provider_desc()}
                  {:else if providerModels.length === 1}
                    {m.governance_provider_model_count_one({ count: providerModels.length })}
                  {:else}
                    {m.governance_provider_model_count_other({ count: providerModels.length })}
                  {/if}
                </div>
              </div>
            </div>
          </div>
          <table
            class="w-full text-sm"
            aria-label={m.governance_models_table_aria({ provider: providerName(pid) })}
          >
            <thead class="sr-only">
              <tr>
                <th scope="col">{m.governance_col_allow()}</th>
                <th scope="col">{m.governance_col_model()}</th>
                <th scope="col">{m.governance_col_default()}</th>
              </tr>
            </thead>
            <tbody>
              {#each providerModels as model (model.id)}
                {@const sel = modelSelections.get(model.id)}
                {@const includedViaProvider = isProviderSelected}
                {@const effectivelySelected = includedViaProvider || (sel?.selected ?? false)}
                <tr class="border-default border-t {includedViaProvider ? 'bg-secondary/30' : ''}">
                  <td class="w-14 px-4 py-2.5">
                    <Switch
                      checked={effectivelySelected}
                      disabled={includedViaProvider}
                      onCheckedChange={(v) => toggleModelSelected(model.id, v)}
                      aria-label={m.governance_model_allow_aria({
                        name: model.nickname ?? model.name
                      })}
                    />
                  </td>
                  <td class="px-4 py-2.5">
                    <span class={includedViaProvider ? "text-secondary" : ""}>
                      {model.nickname ?? model.name}
                    </span>
                    {#if includedViaProvider}
                      <span class="text-tertiary ml-1.5 text-xs">{m.governance_via_provider()}</span
                      >
                    {/if}
                  </td>
                  <td class="w-20 px-4 py-2.5">
                    <div class="flex items-center gap-2">
                      <RadioGroup.Item
                        value={model.id}
                        id={`default-${model.id}`}
                        disabled={!effectivelySelected}
                        aria-label={m.governance_model_set_default_aria({
                          name: model.nickname ?? model.name
                        })}
                      />
                      <Label for={`default-${model.id}`} class="text-secondary text-xs">
                        {m.governance_default_label()}
                      </Label>
                    </div>
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </fieldset>
      {/each}
    </RadioGroup.Root>
    {#if effectiveModelIds.size === 0}
      <p class="text-destructive flex items-center gap-2 text-sm" role="alert">
        <AlertCircle class="h-4 w-4 shrink-0" aria-hidden="true" />
        {m.governance_models_error_none()}
      </p>
    {:else if !defaultValid}
      <p class="text-destructive flex items-center gap-2 text-sm" role="alert">
        <AlertCircle class="h-4 w-4 shrink-0" aria-hidden="true" />
        {m.governance_models_error_default_invalid()}
      </p>
    {/if}
  {:else}
    <p id="models-help" class="text-secondary text-sm">
      {m.governance_models_help_disabled()}
    </p>
  {/if}
</PolicySection>

// frontend/apps/web-next/src/features/admin/governance/model-restriction-section.tsx
"use client";

import { AlertCircle, Cpu } from "lucide-react";
import { useTranslations } from "next-intl";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Switch } from "@/components/ui/switch";
import { PolicySection } from "./policy-section";
import type { PolicyDraft } from "./use-policy-draft";

export function ModelRestrictionSection({ draft }: { draft: PolicyDraft }) {
  const t = useTranslations();
  const {
    modelsEnabled,
    setModelsEnabled,
    modelsByProvider,
    modelSelections,
    providerSelections,
    effectiveModelIds,
    defaultModelId,
    modelsSummary,
    defaultValid,
    badgeVariant,
    providerName,
    setSingleDefault,
    toggleModelSelected,
    toggleProvider
  } = draft;

  return (
    <PolicySection
      id="models"
      title={t("governance_models_heading")}
      description={t("governance_models_section_desc")}
      summary={modelsSummary}
      summaryVariant={badgeVariant(modelsEnabled, effectiveModelIds.size > 0 && defaultValid)}
      icon={<Cpu className="size-5" />}
    >
      <div className="flex items-center justify-between gap-3">
        <Label htmlFor="models-enabled" className="text-sm font-medium">
          {t("governance_models_toggle_label")}
        </Label>
        <Switch
          id="models-enabled"
          checked={modelsEnabled}
          onCheckedChange={setModelsEnabled}
          aria-describedby="models-help"
        />
      </div>

      {modelsEnabled ? (
        <>
          <p id="models-help" className="text-muted-foreground text-sm">
            {t("governance_models_help_enabled")}
          </p>
          {/* One default model across all providers, so a single radio group wraps every table. */}
          <RadioGroup
            value={defaultModelId ?? ""}
            onValueChange={(value) => value && setSingleDefault(value)}
            className="gap-3"
          >
            {[...modelsByProvider.entries()].map(([pid, providerModels]) => {
              const isProviderSelected = pid !== null && providerSelections.has(pid);
              return (
                <fieldset key={pid ?? "_unprovided"} className="overflow-hidden rounded-lg border">
                  <legend className="sr-only">{providerName(pid)}</legend>
                  <div className="bg-muted flex items-center justify-between gap-3 border-b px-4 py-3">
                    <div className="flex items-center gap-3">
                      {pid !== null ? (
                        <Switch
                          checked={isProviderSelected}
                          onCheckedChange={(value) => toggleProvider(pid, value)}
                          aria-label={t("governance_provider_allow_all_aria", {
                            provider: providerName(pid)
                          })}
                        />
                      ) : (
                        <div className="w-8" aria-hidden="true" />
                      )}
                      <div>
                        <div className="text-foreground text-sm font-semibold">
                          {providerName(pid)}
                        </div>
                        <div className="text-muted-foreground text-xs">
                          {isProviderSelected
                            ? t("governance_provider_all_allowed")
                            : pid === null
                              ? t("governance_provider_no_provider_desc")
                              : providerModels.length === 1
                                ? t("governance_provider_model_count_one", {
                                    count: providerModels.length
                                  })
                                : t("governance_provider_model_count_other", {
                                    count: providerModels.length
                                  })}
                        </div>
                      </div>
                    </div>
                  </div>
                  <table
                    className="w-full text-sm"
                    aria-label={t("governance_models_table_aria", { provider: providerName(pid) })}
                  >
                    <thead className="sr-only">
                      <tr>
                        <th scope="col">{t("governance_col_allow")}</th>
                        <th scope="col">{t("governance_col_model")}</th>
                        <th scope="col">{t("governance_col_default")}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {providerModels.map((model) => {
                        const includedViaProvider = isProviderSelected;
                        const effectivelySelected =
                          includedViaProvider || (modelSelections[model.id]?.selected ?? false);
                        const modelName = model.nickname ?? model.name;
                        return (
                          <tr
                            key={model.id}
                            className={`border-t ${includedViaProvider ? "bg-muted/40" : ""}`}
                          >
                            <td className="w-14 px-4 py-2.5">
                              <Switch
                                checked={effectivelySelected}
                                disabled={includedViaProvider}
                                onCheckedChange={(value) => toggleModelSelected(model.id, value)}
                                aria-label={t("governance_model_allow_aria", { name: modelName })}
                              />
                            </td>
                            <td className="px-4 py-2.5">
                              <span className={includedViaProvider ? "text-muted-foreground" : ""}>
                                {modelName}
                              </span>
                              {includedViaProvider && (
                                <span className="text-muted-foreground ml-1.5 text-xs">
                                  {t("governance_via_provider")}
                                </span>
                              )}
                            </td>
                            <td className="w-20 px-4 py-2.5">
                              <div className="flex items-center gap-2">
                                <RadioGroupItem
                                  value={model.id}
                                  id={`default-${model.id}`}
                                  disabled={!effectivelySelected}
                                  aria-label={t("governance_model_set_default_aria", {
                                    name: modelName
                                  })}
                                />
                                <Label
                                  htmlFor={`default-${model.id}`}
                                  className="text-muted-foreground text-xs"
                                >
                                  {t("governance_default_label")}
                                </Label>
                              </div>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </fieldset>
              );
            })}
          </RadioGroup>
          {effectiveModelIds.size === 0 ? (
            <p className="text-destructive flex items-center gap-2 text-sm" role="alert">
              <AlertCircle className="size-4 shrink-0" aria-hidden="true" />
              {t("governance_models_error_none")}
            </p>
          ) : !defaultValid ? (
            <p className="text-destructive flex items-center gap-2 text-sm" role="alert">
              <AlertCircle className="size-4 shrink-0" aria-hidden="true" />
              {t("governance_models_error_default_invalid")}
            </p>
          ) : null}
        </>
      ) : (
        <p id="models-help" className="text-muted-foreground text-sm">
          {t("governance_models_help_disabled")}
        </p>
      )}
    </PolicySection>
  );
}
