// frontend/apps/web/src/routes/(app)/admin/personal-assistant/configuration/PolicyConfirmDialog.svelte
<!--
    Copyright (c) 2026 Sundsvalls Kommun

    Licensed under the MIT License.
-->

<script lang="ts">
  import { Button } from "$lib/components/ui/button/index.js";
  import * as Dialog from "$lib/components/ui/dialog/index.js";
  import { m } from "$lib/paraglide/messages";

  type PendingConfirm = { messages: string[]; submit: () => Promise<void> };
  type Props = {
    pendingConfirm: PendingConfirm | null;
    saving: boolean;
  };

  let { pendingConfirm = $bindable(), saving }: Props = $props();
</script>

<Dialog.Root
  open={pendingConfirm !== null}
  onOpenChange={(o) => {
    if (!o) pendingConfirm = null;
  }}
>
  <Dialog.Content>
    <Dialog.Header>
      <Dialog.Title>{m.governance_confirm_title()}</Dialog.Title>
      <Dialog.Description>
        {m.governance_confirm_desc()}
      </Dialog.Description>
    </Dialog.Header>
    <ul class="list-disc space-y-1 pl-6 text-sm">
      {#each pendingConfirm?.messages ?? [] as msg (msg)}
        <li>{msg}</li>
      {/each}
    </ul>
    <Dialog.Footer>
      <Button variant="outline" onclick={() => (pendingConfirm = null)} disabled={saving}>
        {m.cancel()}
      </Button>
      <Button onclick={() => pendingConfirm?.submit()} disabled={saving} aria-busy={saving}>
        {saving ? m.governance_saving() : m.governance_confirm_and_save()}
      </Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>

// frontend/apps/web-next/src/features/admin/governance/policy-confirm-dialog.tsx
"use client";

import { useTranslations } from "next-intl";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog";
import type { ConfirmKey } from "./policy-draft";

export function PolicyConfirmDialog({
  pending,
  saving,
  onCancel,
  onConfirm
}: {
  /** Translation keys for the risky changes about to be applied; null = closed. */
  pending: ConfirmKey[] | null;
  saving: boolean;
  onCancel: () => void;
  onConfirm: () => void;
}) {
  const t = useTranslations();

  return (
    <Dialog open={pending !== null} onOpenChange={(open) => !open && onCancel()}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("governance_confirm_title")}</DialogTitle>
          <DialogDescription>{t("governance_confirm_desc")}</DialogDescription>
        </DialogHeader>
        <ul className="list-disc space-y-1 pl-6 text-sm">
          {(pending ?? []).map((key) => (
            <li key={key}>{t(key)}</li>
          ))}
        </ul>
        <DialogFooter>
          <Button variant="outline" onClick={onCancel} disabled={saving}>
            {t("cancel")}
          </Button>
          <Button onClick={onConfirm} disabled={saving} aria-busy={saving}>
            {saving ? t("governance_saving") : t("governance_confirm_and_save")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
