// frontend/apps/web-next/src/features/admin/users/user-actions.tsx
"use client";

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { MoreVertical, Pencil, Trash2, UserMinus, UserPlus } from "lucide-react";
import { useTranslations } from "next-intl";
import { useState } from "react";
import { useAppContext } from "@/components/providers/app-context";
import { ConfirmDialogControlled } from "@/components/composites/confirm-dialog";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu";
import { browserApi } from "@/lib/api/browser";
import { unwrap } from "@/lib/api/errors";
import { toastApiError } from "@/lib/api/toast";
import { UserEditorDialog } from "./user-editor";
import type { AdminUser } from "./users";

export function UserActions({ user }: { user: AdminUser }) {
  const t = useTranslations();
  const { user: currentUser } = useAppContext();
  const queryClient = useQueryClient();
  const [showEdit, setShowEdit] = useState(false);
  const [showDelete, setShowDelete] = useState(false);

  const invalidate = () => queryClient.invalidateQueries({ queryKey: ["admin-users"] });
  const isSelf = user.id === currentUser.id;
  const isActive = user.state === "active" || user.state === "invited";

  const setState = useMutation({
    mutationFn: (action: "deactivate" | "reactivate") => {
      if (!user.username) throw new Error("missing username");
      const path =
        action === "deactivate"
          ? ("/api/v1/admin/users/{username}/deactivate" as const)
          : ("/api/v1/admin/users/{username}/reactivate" as const);
      return unwrap(browserApi.POST(path, { params: { path: { username: user.username } } }));
    },
    onSuccess: invalidate,
    onError: (error) => toastApiError(error, t)
  });

  const deleteUser = useMutation({
    mutationFn: () =>
      unwrap(browserApi.DELETE("/api/v1/users/admin/{id}/", { params: { path: { id: user.id } } })),
    onSuccess: () => {
      invalidate();
      setShowDelete(false);
    },
    onError: (error) => toastApiError(error, t)
  });

  return (
    <>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="ghost" size="icon" aria-label={t("actions")}>
            <MoreVertical className="size-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onSelect={() => setShowEdit(true)}>
            <Pencil className="size-4" /> {t("edit_user")}
          </DropdownMenuItem>
          {isActive ? (
            <DropdownMenuItem
              disabled={isSelf || setState.isPending}
              onSelect={() => setState.mutate("deactivate")}
            >
              <UserMinus className="size-4" /> {t("deactivate_user")}
            </DropdownMenuItem>
          ) : (
            <DropdownMenuItem
              disabled={setState.isPending}
              onSelect={() => setState.mutate("reactivate")}
            >
              <UserPlus className="size-4" /> {t("reactivate_user")}
            </DropdownMenuItem>
          )}
          <DropdownMenuItem
            variant="destructive"
            disabled={isSelf}
            onSelect={() => setShowDelete(true)}
          >
            <Trash2 className="size-4" /> {t("delete_user")}
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      <UserEditorDialog open={showEdit} onOpenChange={setShowEdit} user={user} />
      <ConfirmDialogControlled
        open={showDelete}
        onOpenChange={setShowDelete}
        title={t("delete_user")}
        description={`${t("do_you_really_want_to_delete")} ${user.email}?`}
        confirmLabel={deleteUser.isPending ? t("deleting") : t("delete")}
        pending={deleteUser.isPending}
        onConfirm={() => deleteUser.mutate()}
      />
    </>
  );
}

// frontend/apps/web/src/routes/(app)/admin/users/UserActions.svelte
<!--
    Copyright (c) 2024 Sundsvalls Kommun

    Licensed under the MIT License.
-->

<script lang="ts">
  import type { User } from "@eneo/eneo-js";
  import { Button } from "$lib/components/ui/button/index.js";
  import * as AlertDialog from "$lib/components/ui/alert-dialog/index.js";
  import * as DropdownMenu from "$lib/components/ui/dropdown-menu/index.js";
  import { dialogLayout } from "$lib/components/dialogLayout.js";
  import { MoreVertical, Edit, UserMinus, UserPlus, Trash2 } from "@lucide/svelte";
  import { invalidate } from "$app/navigation";
  import UserEditor from "./editor/UserEditor.svelte";
  import { getAppContext } from "$lib/core/AppContext";
  import { getEneo } from "$lib/core/Eneo";
  import { m } from "$lib/paraglide/messages";

  const eneo = getEneo();

  // Svelte 5 runes mode: use $props() instead of export let
  let { user } = $props<{ user: User }>();

  async function deleteUser() {
    isProcessing = true;
    try {
      await eneo.users.delete(user);
      invalidate("admin:users"); // Stable dependency key
      showDeleteDialog = false;
    } catch (e) {
      console.error(e);
    }
    isProcessing = false;
  }

  async function deactivateUser() {
    try {
      await eneo.users.deactivate({ user: { username: user.username } });
      invalidate("admin:users"); // Stable dependency key
    } catch (e) {
      console.error(e);
    }
  }

  async function reactivateUser() {
    try {
      await eneo.users.reactivate({ user: { username: user.username } });
      invalidate("admin:users"); // Stable dependency key
    } catch (e) {
      console.error(e);
    }
  }

  const { user: currentUser } = getAppContext();

  // Determine button visibility based on user state
  const isActive = $derived(user.state === "active" || user.state === "invited");
  const isInactive = $derived(user.state === "inactive");

  let isProcessing = $state(false);
  let showEditDialog = $state(false);
  let showDeleteDialog = $state(false);
</script>

<DropdownMenu.Root>
  <DropdownMenu.Trigger>
    {#snippet child({ props })}
      <Button {...props} variant="ghost" size="icon" aria-label={m.actions()}>
        <MoreVertical size={16} />
      </Button>
    {/snippet}
  </DropdownMenu.Trigger>

  <DropdownMenu.Content align="end">
    <!-- Edit action - always available -->
    <DropdownMenu.Item
      onSelect={() => {
        showEditDialog = true;
      }}
    >
      <Edit size={16} />
      {m.edit_user()}
    </DropdownMenu.Item>

    <!-- Deactivate - only for active/invited users -->
    {#if isActive}
      <DropdownMenu.Item disabled={user.id === currentUser.id} onSelect={deactivateUser}>
        <UserMinus size={16} />
        {m.deactivate_user()}
      </DropdownMenu.Item>
    {/if}

    <!-- Reactivate - only for inactive users -->
    {#if isInactive}
      <DropdownMenu.Item onSelect={reactivateUser}>
        <UserPlus size={16} />
        {m.reactivate_user()}
      </DropdownMenu.Item>
    {/if}

    <!-- Delete - always available but destructive -->
    <DropdownMenu.Item
      variant="destructive"
      disabled={user.id === currentUser.id}
      onSelect={() => {
        showDeleteDialog = true;
      }}
    >
      <Trash2 size={16} />
      {m.delete_user()}
    </DropdownMenu.Item>
  </DropdownMenu.Content>
</DropdownMenu.Root>

<!-- Edit Dialog - hide built-in trigger since we control it from dropdown -->
<UserEditor {user} mode="update" hideTrigger={true} bind:open={showEditDialog}></UserEditor>

<!-- Delete Confirmation Dialog -->
<AlertDialog.Root bind:open={showDeleteDialog}>
  <AlertDialog.Content class={dialogLayout.content("small")}>
    <AlertDialog.Header class={dialogLayout.header}>
      <AlertDialog.Title>{m.delete_user()}</AlertDialog.Title>
      <AlertDialog.Description>
        {m.do_you_really_want_to_delete()}
        <span class="italic">{user.email}</span>?
      </AlertDialog.Description>
    </AlertDialog.Header>

    <AlertDialog.Footer class={dialogLayout.footer}>
      <AlertDialog.Cancel>{m.cancel()}</AlertDialog.Cancel>
      <Button variant="destructive" onclick={deleteUser}>
        {isProcessing ? m.deleting() : m.delete()}
      </Button>
    </AlertDialog.Footer>
  </AlertDialog.Content>
</AlertDialog.Root>
