// frontend/apps/web-next/src/features/api-keys/expiring-keys-notification.tsx
"use client";

import { useQuery } from "@tanstack/react-query";
import { Bell, ChevronRight } from "lucide-react";
import Link from "next/link";
import { useTranslations } from "next-intl";
import { useAppContext } from "@/components/providers/app-context";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu";
import { browserApi } from "@/lib/api/browser";
import { unwrap } from "@/lib/api/errors";
import { summaryToDisplayItems, type ExpiringKeyDisplayItem } from "./expiration-utils";

const MAX_VISIBLE = 5;

function hasDuplicateName(name: string, items: ExpiringKeyDisplayItem[]): boolean {
  return items.filter((item) => item.name === name).length > 1;
}

function itemExpiryText(
  item: ExpiringKeyDisplayItem,
  t: ReturnType<typeof useTranslations>
): string {
  if (item.level === "expired") return t("api_keys_expiring_item_expired");
  if (item.daysRemaining === 0) return t("api_keys_expiring_item_today");
  if (item.daysRemaining === 1) return t("api_keys_expiring_item_tomorrow");
  return t("api_keys_expiring_item_days", { days: item.daysRemaining });
}

export function ExpiringKeysNotification() {
  const t = useTranslations();
  const { settings } = useAppContext();
  const featureEnabled = settings.api_key_expiry_notifications !== false;

  const preferences = useQuery({
    queryKey: ["api-key-notification-preferences"],
    queryFn: () => unwrap(browserApi.GET("/api/v1/api-keys/notification-preferences")),
    enabled: featureEnabled,
    staleTime: 60_000
  });
  const subscriptions = useQuery({
    queryKey: ["api-key-notification-subscriptions"],
    queryFn: () => unwrap(browserApi.GET("/api/v1/api-keys/notification-subscriptions")),
    enabled: featureEnabled,
    staleTime: 60_000
  });

  const daysWindow = Math.max(...(preferences.data?.days_before_expiry ?? [30]), 1);
  const hasSubscriptions = (subscriptions.data?.items.length ?? 0) > 0;
  const summary = useQuery({
    queryKey: ["api-keys", "expiring-soon", "subscribed", daysWindow],
    queryFn: () =>
      unwrap(
        browserApi.GET("/api/v1/api-keys/expiring-soon", {
          params: { query: { days: daysWindow, mode: "subscribed" } }
        })
      ),
    enabled: featureEnabled && (preferences.data?.enabled ?? false) && hasSubscriptions,
    staleTime: 60_000
  });

  const items = summary.data ? summaryToDisplayItems(summary.data.items) : [];
  if (items.length === 0) return null;

  const counts = summary.data?.counts_by_severity ?? {};
  const expiredCount = counts.expired ?? 0;
  const urgentCount = counts.urgent ?? 0;
  const warningCount = counts.warning ?? 0;
  const hasUrgent = expiredCount + urgentCount > 0;
  const visibleItems = items.slice(0, MAX_VISIBLE);
  const overflowCount = items.length - MAX_VISIBLE;

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="ghost"
          size="icon"
          aria-label={t("api_keys_expiring_bell_title")}
          className="relative"
        >
          <Bell className="size-4" />
          <span
            className={`absolute top-1.5 right-1.5 size-2 rounded-full ${
              hasUrgent ? "bg-destructive" : "bg-warning"
            }`}
          />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-96 p-2">
        <div className="flex flex-col gap-2" role="status">
          <div className="px-2">
            <p className="font-medium">{t("api_keys_expiring_bell_title")}</p>
            <p className="text-muted-foreground text-xs">
              {expiredCount > 0
                ? t("api_keys_expiring_bell_summary_expired", { count: expiredCount })
                : null}
              {expiredCount > 0 && urgentCount > 0 ? ", " : null}
              {urgentCount > 0
                ? t("api_keys_expiring_bell_summary_urgent", { count: urgentCount })
                : null}
              {(expiredCount > 0 || urgentCount > 0) && warningCount > 0 ? ", " : null}
              {warningCount > 0
                ? t("api_keys_expiring_bell_summary_warning", { count: warningCount })
                : null}
            </p>
          </div>
          <div
            className={`rounded-lg border px-2 py-1 shadow-sm ${
              hasUrgent ? "bg-destructive/5" : warningCount > 0 ? "bg-warning/5" : "bg-card"
            }`}
          >
            {visibleItems.map((item) => (
              <div
                key={item.id}
                className="flex items-center justify-between gap-3 border-b px-1 py-2 last:border-b-0"
              >
                <div className="flex min-w-0 items-center gap-2">
                  <span
                    aria-hidden="true"
                    className={`shrink-0 rounded-full ${
                      item.level === "expired" || item.level === "urgent"
                        ? "bg-destructive size-2.5"
                        : "bg-warning size-2"
                    }`}
                  />
                  <span className="truncate text-sm" title={item.name}>
                    {item.name}
                  </span>
                  {item.keySuffix && hasDuplicateName(item.name, items) ? (
                    <span className="text-muted-foreground shrink-0 font-mono text-xs">
                      ...{item.keySuffix}
                    </span>
                  ) : null}
                </div>
                <span
                  className={`shrink-0 text-xs ${
                    item.level === "expired" || item.level === "urgent"
                      ? "text-destructive"
                      : "text-warning"
                  }`}
                >
                  {itemExpiryText(item, t)}
                </span>
              </div>
            ))}
            {overflowCount > 0 ? (
              <div className="text-muted-foreground px-1 py-2 text-xs">
                {t("api_keys_expiring_bell_more", { count: overflowCount })}
              </div>
            ) : null}
          </div>
          <Button asChild variant="ghost" className="justify-between">
            <Link href="/account/api-keys">
              {t("api_keys_expiring_bell_manage")}
              <ChevronRight className="size-4" />
            </Link>
          </Button>
        </div>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// frontend/apps/web/src/lib/features/api-keys/ExpiringKeysNotification.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { getExpiringKeysStore } from "./expiringKeysStore";
  import { IconChevronRight } from "@intric/icons/chevron-right";
  import { m } from "$lib/paraglide/messages";
  import { localizeHref } from "$lib/paraglide/runtime";

  const { state, refresh } = getExpiringKeysStore();
  const { displayItems, summary, hasUrgent } = state;

  const MAX_VISIBLE = 5;

  // Refresh on mount (respects 60s TTL) — ensures fresh data when dropdown opens
  onMount(() => {
    refresh();
  });

  // Detect duplicate names to show key suffix for disambiguation
  function hasDuplicateName(name: string, items: typeof $displayItems): boolean {
    return items.filter((i) => i.name === name).length > 1;
  }
</script>

{#if $displayItems.length > 0}
  {@const counts = $summary?.counts_by_severity}
  {@const expiredCount = counts?.expired ?? 0}
  {@const urgentCount = counts?.urgent ?? 0}
  {@const warningCount = counts?.warning ?? 0}
  {@const visibleItems = $displayItems.slice(0, MAX_VISIBLE)}
  {@const overflowCount = $displayItems.length - MAX_VISIBLE}
  <div class="flex flex-col gap-1 px-2 py-2" role="status">
    <span class="pl-3 font-medium">{m.api_keys_expiring_bell_title()}</span>

    {#if expiredCount > 0 || urgentCount > 0 || warningCount > 0}
      <span class="pl-3 text-xs text-secondary">
        {#if expiredCount > 0}
          <span class="text-negative">{m.api_keys_expiring_bell_summary_expired({ count: expiredCount })}</span>
        {/if}
        {#if urgentCount > 0}
          {#if expiredCount > 0}<span>, </span>{/if}
          <span class="text-negative">{m.api_keys_expiring_bell_summary_urgent({ count: urgentCount })}</span>
        {/if}
        {#if warningCount > 0}
          {#if expiredCount > 0 || urgentCount > 0}<span>, </span>{/if}
          <span class="text-caution">{m.api_keys_expiring_bell_summary_warning({ count: warningCount })}</span>
        {/if}
      </span>
    {/if}

    <div
      class="border-default ring-default min-h-10 items-center justify-between rounded-lg border px-3 py-2 shadow
             {$hasUrgent ? 'bg-negative/5' : warningCount > 0 ? 'bg-caution/5' : 'bg-primary'}"
    >
      {#each visibleItems as item (item.id)}
        <div
          class="border-dimmer flex items-center justify-between gap-x-3 border-b px-2 py-1.5 whitespace-nowrap last-of-type:border-b-0"
        >
          <div class="flex items-center gap-2 flex-shrink truncate pr-4">
            <span
              aria-hidden="true"
              class="inline-block flex-shrink-0 rounded-full {item.level === 'expired' || item.level === 'urgent'
                ? 'bg-negative h-2.5 w-2.5'
                : 'bg-caution h-2 w-2'}"
            ></span>
            <span
              class="truncate {item.level === 'expired' ? 'font-medium' : ''}"
              title={item.name}
            >
              {item.name}
            </span>
            {#if item.keySuffix && hasDuplicateName(item.name, $displayItems)}
              <span class="text-tertiary text-xs font-mono flex-shrink-0"
                >&middot; ...{item.keySuffix}</span
              >
            {/if}
          </div>
          <div class="flex-shrink-0 text-right">
            {#if item.level === "expired"}
              <span class="text-negative font-medium text-xs"
                >{m.api_keys_expiring_item_expired()}</span
              >
            {:else if item.daysRemaining === 0}
              <span class="text-negative text-xs">{m.api_keys_expiring_item_today()}</span>
            {:else if item.daysRemaining === 1}
              <span class="text-negative text-xs">{m.api_keys_expiring_item_tomorrow()}</span>
            {:else}
              <span
                class="{item.level === 'urgent' ? 'text-negative' : 'text-caution'} text-xs"
              >
                {m.api_keys_expiring_item_days({ days: item.daysRemaining })}
              </span>
            {/if}
          </div>
        </div>
      {/each}

      {#if overflowCount > 0}
        <div class="px-2 py-1.5 text-xs text-secondary">
          {m.api_keys_expiring_bell_more({ count: overflowCount })}
        </div>
      {/if}
    </div>

    <a
      href={localizeHref("/account/api-keys")}
      class="flex items-center justify-between gap-2 rounded-md px-3 py-2 min-h-[44px]
             text-sm font-medium text-accent-default hover:bg-hover
             focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-default/50
             transition-colors"
    >
      {m.api_keys_expiring_bell_manage()}
      <IconChevronRight class="h-4 w-4" />
    </a>
  </div>
{/if}
